# -*- coding: utf-8 -*-
"""REAP / AlphaProof 研究导航 —— 数据模型 v2（学习顺序 / 开发顺序 / 上下文映射 + 文件级深链）。

路径机器代号:
  wsl    = 笔记本 WSL (zhai@LAPTOP-IR9BS02N, distro Ubuntu-D)
  remote = my-new-linux (a@my-new-linux, F盘=/mnt/gloway, E盘=/mnt/lexar)

本文件的 GitHub 深链均已用仓库 tree API 校验过文件存在（2026-09-20）。
"""

# ---------- GitHub 仓库常量 ----------
AP = "https://github.com/wufuju2023-cell/alpha-proof-original-math-version"
APM = "https://github.com/wufuju2023-cell/alphaproof-official-materials"
NANO = "https://github.com/kripner/nanoproof"
NANOF = "https://github.com/wufuju2023-cell/nanoproof-value-head"
GAP = "https://github.com/wufuju2023-cell/gap-advance-plan-of-nano-proof-v1-m1"
REAP = "https://github.com/frenzymath/reap"
REAPS = "https://github.com/wufuju2023-cell/reap-source-code-explain"
REAPP = "https://github.com/wufuju2023-cell/reap-alpha-proof"
RNUM = "https://github.com/wufuju2023-cell/reap-new-update-model"
RSI = "https://github.com/wufuju2023-cell/reap-rsi-public"
TTT = "https://github.com/wufuju2023-cell/new-reap-mcts-ttt-public"
AG = "https://github.com/wufuju2023-cell/reap-agentic-v1-1"
TOOL = "https://github.com/wufuju2023-cell/v1-1-agentic-tool"
P914 = "https://github.com/wufuju2023-cell/9-14-project-my-new-linux"
MARL = "https://github.com/wufuju2023-cell/multi-agent-rl-alpha-proof"
RGAP = "https://github.com/wufuju2023-cell/reap-gap-advance-alpha-proof"
MLT = "https://github.com/wufuju2023-cell/ml-theory-reference"
MCTS = "https://github.com/wufuju2023-cell/mcts-theory-learning"
LEAN = "https://github.com/wufuju2023-cell/Lean-source-code-learning-to-know-reap"
JEV = "https://github.com/wufuju2023-cell/jev-alpha-proof-analysis"
ROAD = "https://github.com/wufuju2023-cell/reap-roadmap"
HSY = "https://github.com/hsy221329/hsy-alphaproof-public"


def B(repo, branch, path):
    return f"{repo}/blob/{branch}/{path}"


def T(repo, branch, path=""):
    return f"{repo}/tree/{branch}/{path}" if path else f"{repo}/tree/{branch}"


def C(cid, title, desc, tags=(), paths=(), links=(), quick=(), reads="", lead=""):
    return {"id": cid, "title": title, "desc": desc, "tags": list(tags),
            "paths": [tuple(p) for p in paths],
            "links": [tuple(l) for l in links],
            "quick": [tuple(q) for q in quick], "reads": reads, "lead": lead}


META = {
    "title": "REAP / AlphaProof 研究导航",
    "subtitle": "主线 V1 / V1-1 · 学习顺序 · 开发顺序 · 模块上下文 · 文件级深链",
    "generated": "2026-09-20",
    "wsl_distro": "Ubuntu-D",
}

# (标题, 正文, 是否仅私有版显示)
NOTES = [
    ("价值头语义（重要更正）",
     "权威定义见 AlphaProof 分析档案 00-overview：d(s) = -V(s) ≥ 0 是「期望剩余步数」（长分支取 max），"
     "不是百分比。旧 V1 spec/历史文档中「价值头输出百分比」的说法与原文不符：若要输出百分比，"
     "对象应改写为 P(解出 | 预算 B)，且损失与解码都要重定义。", False),
    ("主线与支线",
     "主线 = V1（7B policy + 价值头 + on-demand RTTT）与 V1-1（agentic-tool 工具环 + CPU/GPU 桥）；"
     "多智能体 RL（MARL）是下一步主线（已有形式化，代码待补）；V2（元动作/Eff/塔）为实验性；"
     "Jev 与校准分析仅为支线参考。", False),
    ("执行状态口径（本次审计）",
     "已跑通·有实验 = 有 JSON/日志/回执等产物；代码待验证 = 代码存在但只有契约测试或未端到端跑；"
     "原型 = 能跑但功能不完整（如 V2 不是证明树）；仅文档 = 无实现；已过时 = 有更新的纠正版。"
     "全部判据见「执行状态审计」「实验台账」「已过时文档」三张表。", False),
    ("Lean 版本",
     "主线 = Lean 4.28：reap=v4.28.0-rc1、new-v1-gather-source-code-cpu=v4.28.0-rc1、"
     "v1-1-agentic-tool/cpulean=v4.28.0、mathlib4=v4.28.0。"
     "例外：reap-agentic-v1-1/cpulean=v4.33.0-rc2；formal-imo / miniF2F / Nexus 用 v4.27.0。", False),
    ("E 盘现状",
     "/mnt/e 当前为空（E 盘掉线/未挂载），alpha-proof-original-math-version 的本地符号链接已断。"
     "请用 .wsl-backup 目录或 F 盘镜像同名内容。", True),
    ("私有仓库",
     "reap-alpha-proof 与 reap-new-update-model-value-head 为私有仓库（登录后可开）；"
     "其余仓库均公开（本篇 17 个 + hsy 的 1 个）。", True),
]

# 快速阅读顺序（顶部表格）
QUICK = [
    ("1. 读原理（AlphaProof 怎么工作）",
     "档案 00→01→03→02→04→06→05→07→08；深挖 10/13/14；重建路线 09→19→20",
     ["c_dossier"]),
    ("2. 读源码（Reap 怎么实现）",
     "reap-source-code-explain 01→02→03→04→05→06；无 Lean 基础先看 01",
     ["c_reap_source"]),
    ("3. 看差距与路线（nano / REAP vs AlphaProof）",
     "nano 分析 00→02→03→05→09；REAP 补充 00-index→04→06",
     ["c_nano_analysis", "c_reap_gap"]),
    ("4. 跑/改 V1（主线）",
     "v1-spec 00→01→02→04→05→07；methods 00→04；实验档案 v1-result 复现",
     ["c_v1_spec", "c_v1_result"]),
    ("5. 改价值头",
     "档案 02+12 → app/VALUE_HEAD.md → HF reap-value-head-v1-scaling → MCTS 笔记 9",
     ["c_v1_value_head"]),
    ("6. V1-1 agentic-tool（主线）",
     "9-14-plan 00→01→02→03 → reap-agentic-v1-1 README → v1-1-agentic-tool",
     ["c_914_plan", "c_agentic_repo"]),
    ("7. 多智能体扩展（下一步主线）/ V2（实验）",
     "MARL 1-glance → 9-14 M3（骨架）；V2：explain 7→8 → v2 spec 00→04 → v2 code",
     ["c_marl", "c_v2_spec"]),
    ("8. Jev 校准决策（支线参考）",
     "Jev 00→03→12；分析子系列 00→02→03→04；实验设计看 07",
     ["c_jev_ap"]),
]

# 三个总表：学习顺序 / 开发顺序 / 模块→上下文
GUIDES = [
    {"id": "g-learn", "title": "整体学习顺序（S0→S7）",
     "cols": ["阶段", "目标", "先读（按序）", "完成标志"],
     "rows": [
         ["S0 Lean 基础（可选）",
          "能读 Lean4 源码级文档",
          f"[LL-00]({B(LEAN,'main','LL-00-README-plan.md')}) → [LL-02]({B(LEAN,'main','LL-02-expr-levels.md')}) → [LL-03]({B(LEAN,'main','LL-03-kernel-type-checker.md')}) → [LL-06]({B(LEAN,'main','LL-06-tactic-framework.md')})",
          "能解释 Expr / MVar / tactic / kernel"],
         ["S1 AlphaProof 原理",
          "完整理解原系统",
          f"[00]({B(AP,'main','00-overview.md')}) → [01]({B(AP,'main','01-lean-env.md')}) → [03]({B(AP,'main','03-search.md')}) → [02]({B(AP,'main','02-proof-network.md')}) → [04]({B(AP,'main','04-pretrain-sft.md')}) → [06]({B(AP,'main','06-main-rl.md')}) → [05]({B(AP,'main','05-autoformalize.md')}) → [07]({B(AP,'main','07-ttrl.md')}) → [08]({B(AP,'main','08-benchmarks.md')})",
          "能复述 value target / PUCT / AND 节点"],
         ["S2 开源实现",
          "读懂 reap 源码与 nano 差距",
          f"[reap-source 01]({B(REAPS,'main','01-lean4-from-zero.md')}) → [02]({B(REAPS,'main','02-architecture-overview.md')}) → [04]({B(REAPS,'main','04-proof-state-step.md')}) → [06]({B(REAPS,'main','06-mcts-core.md')})；[nano 分析 00]({B(GAP,'main','00-overview.md')}) → [03]({B(GAP,'main','03-gaps.md')})",
          "能改动一处搜索逻辑并跑测试"],
         ["S3 V1 规格",
          "能起服务、跑一轮 RTTT",
          f"[plan 00]({B(RNUM,'master','plan/00-index.md')}) → [05]({B(RNUM,'master','plan/05-rl-param-update.md')}) → [09]({B(RNUM,'master','plan/09-test-time-training.md')})；[v1-spec 00]({B(RNUM,'master','v1-spec/00-overview.md')}) → [01]({B(RNUM,'master','v1-spec/01-policy-value.md')}) → [02]({B(RNUM,'master','v1-spec/02-mcts-verifier.md')}) → [04]({B(RNUM,'master','v1-spec/04-training.md')}) → [05]({B(RNUM,'master','v1-spec/05-infra.md')}) → [07]({B(RNUM,'master','v1-spec/07-runbook.md')})",
          "按 runbook 完成一次调用内 TTT"],
         ["S4 V1 实验",
          "复现实测结果",
          f"[v1-result README]({B(RNUM,'master','v1-result/README.md')}) → [current/00]({B(RNUM,'master','v1-result/docs/current/00-总设计与阅读地图.md')}) → [01]({B(RNUM,'master','v1-result/docs/current/01-题内在线TTT.md')}) → [04]({B(RNUM,'master','v1-result/docs/current/04-实际实例与验收结果.md')})；复现 [reproduction 00]({B(RNUM,'master','v1-result/reproduction/00-环境与代码.md')}) → [01]({B(RNUM,'master','v1-result/reproduction/01-单题TTT.md')})",
          "Pell / 平方数案例可复现"],
         ["S5 V1-1 工具环",
          "跑通 CPU/GPU 桥与工具环",
          f"[9-14-plan README]({B(P914,'main','9-14-plan/README.md')}) → [00]({B(P914,'main','9-14-plan/00-math-theory.md')}) → [01]({B(P914,'main','9-14-plan/01-architecture-interfaces.md')})；[agentic README]({B(AG,'main','README.md')})；[tool README]({B(TOOL,'main','README.md')})",
          "smoke 3/3 通过，能加一个工具"],
         ["S6 多智能体扩展",
          "掌握信用分配与联合策略",
          f"[MARL 1-glance]({B(MARL,'main','1-glance.md')})；[9-14 M3]({B(P914,'main','9-14-plan/modules/M3-multiagent-experts/README.md')})；[9-14 code m3]({T(P914,'main','9-14-code/m3-multiagent')})",
          "能给出一个可实现的联合奖励方案"],
         ["S7 背景数学（按需）",
          "补足理论工具",
          f"[mcts 1]({B(MCTS,'main','1-.md')}) → [5]({B(MCTS,'main','5-mcts-rl.md')}) → [6]({B(MCTS,'main','6-alpha-proof-mcts-rl.md')}) → [9]({B(MCTS,'main','9-mainrl-ttrl-llm-value-head.md')})；[13 主题]({T(MLT,'main')}) 每篇先读 00 导读",
          "能独立推导 PUCT / Q 变换"],
     ]},
    {"id": "g-dev", "title": "后续开发顺序（M0→M8）与必读上下文",
     "cols": ["里程碑", "做什么", "代码落点", "必读上下文（先读）"],
     "rows": [
         ["M0 环境",
          "Lean 4.28 + mathlib + reap 编译；容器",
          f"[docker/]({T(RNUM,'master','docker')})、[reap]({REAP})",
          f"[environment-spec 02]({B(RNUM,'master','environment-spec/02-toolchain.md')})、[v1-spec 05]({B(RNUM,'master','v1-spec/05-infra.md')})、[07]({B(RNUM,'master','v1-spec/07-runbook.md')})"],
         ["M1 搜索内核",
          "MCTS + checkProof 闭环、AND 节点",
          f"[new-v1-gather-source-code-cpu]({T(RNUM,'master','new-v1-gather-source-code-cpu')})、[reap-source 06]({B(REAPS,'main','06-mcts-core.md')})",
          f"[档案 03]({B(AP,'main','03-search.md')})、[档案 01]({B(AP,'main','01-lean-env.md')})、[v1-spec 02]({B(RNUM,'master','v1-spec/02-mcts-verifier.md')})、[reap-source 04]({B(REAPS,'main','04-proof-state-step.md')})"],
         ["M2 服务化",
          "policy / value / premise 端点与批量化",
          f"[app/]({T(RNUM,'master','app')})、[v1-1-training-example/scripts]({T(RNUM,'master','v1-spec/v1-1-training-example/scripts')})",
          f"[v1-spec 01]({B(RNUM,'master','v1-spec/01-policy-value.md')})、[VALUE_HEAD.md]({B(RNUM,'master','app/VALUE_HEAD.md')})、[档案 02]({B(AP,'main','02-proof-network.md')})"],
         ["M3 数据与课程",
          "变体生成、闸门、难度标定",
          f"[v1-spec 03]({B(RNUM,'master','v1-spec/03-curriculum.md')})、[9-14 m7]({T(P914,'main','9-14-code/m7-curriculum')})",
          f"[档案 05]({B(AP,'main','05-autoformalize.md')})、[nano 03]({B(GAP,'main','03-gaps.md')})、[plan 11]({B(RNUM,'master','plan/11-curriculum-traditional-llm.md')})"],
         ["M4 训练回路",
          "RTTT / GRPO / TTTRL 与价值头更新",
          f"[app/policy_server.py]({B(RNUM,'master','app/policy_server.py')})、[methods]({T(RNUM,'master','v1-spec/v1-1-training-methods')})",
          f"[methods 03]({B(RNUM,'master','v1-spec/v1-1-training-methods/03-rl-spec.md')})、[04]({B(RNUM,'master','v1-spec/v1-1-training-methods/04-tttrl-spec.md')})、[05]({B(RNUM,'master','v1-spec/v1-1-training-methods/05-derive-update-scheme.md')})、[v1-result current/01]({B(RNUM,'master','v1-result/docs/current/01-题内在线TTT.md')})"],
         ["M5 评测门",
          "solve@B、校准、等计算协议",
          f"[v1-spec 06]({B(RNUM,'master','v1-spec/06-eval.md')})、[v1-result]({T(RNUM,'master','v1-result')})",
          f"[档案 08]({B(AP,'main','08-benchmarks.md')})、[20]({B(AP,'main','20-experiment-suite.md')})、[Jev×AP 03]({B(JEV,'main','alpha-proof/03-Proper评分规则与价值目标的统一语言.md')})"],
         ["M6 V1-1 工具环",
          "CPU Lean + GPU 桥 + 工具环证据",
          f"[reap-agentic-v1-1]({AG})、[v1-1-agentic-tool]({TOOL})",
          f"[9-14-plan 01]({B(P914,'main','9-14-plan/01-architecture-interfaces.md')})、[driver]({T(TOOL,'main','driver')})、[9-14-plan 02]({B(P914,'main','9-14-plan/02-milestones-gates.md')})"],
         ["M7 多智能体扩展",
          "专家路由、联合奖励、版本继承",
          f"[9-14 m3]({T(P914,'main','9-14-code/m3-multiagent')})、[9-14 m4]({T(P914,'main','9-14-code/m4-gpu-inference')})",
          f"[MARL 1-glance]({B(MARL,'main','1-glance.md')})、[9-14 M3]({B(P914,'main','9-14-plan/modules/M3-multiagent-experts/README.md')})、[explain 12]({B(RNUM,'master','explain/12-teacher-evolution-co-evolution.md')})"],
         ["M8 V2 实验",
          "元动作 + Eff 通道 + 塔上升",
          f"[v2 code]({T(RNUM,'master','reap-mcts-lean-v2-code-1')})、[lean-v2]({T(RNUM,'master','lean-v2')})",
          f"[v2 spec 00]({B(RNUM,'master','explain/reap-mcts-lean-v2/00-overview.md')}) → [04]({B(RNUM,'master','explain/reap-mcts-lean-v2/04-training-and-metrics.md')})、[explain 7]({B(RNUM,'master','explain/7-reap-v1-v2.md')})"],
     ]},
    {"id": "g-ctx", "title": "模块 → 参考上下文速查",
     "cols": ["模块", "必读上下文", "扩展阅读"],
     "rows": [
         ["搜索内核 / PUCT / AND 节点",
          f"[档案 03]({B(AP,'main','03-search.md')})、[reap-source 04]({B(REAPS,'main','04-proof-state-step.md')})、[06]({B(REAPS,'main','06-mcts-core.md')})",
          f"[档案 14]({B(AP,'main','14-puct-and-temperature.md')})、[mcts 1]({B(MCTS,'main','1-.md')})、[8]({B(MCTS,'main','8-6-q-transform-reason-1.md')})"],
         ["价值头 / 校准 / 删失",
          f"[档案 02]({B(AP,'main','02-proof-network.md')})、[VALUE_HEAD.md]({B(RNUM,'master','app/VALUE_HEAD.md')})、[mcts 9]({B(MCTS,'main','9-mainrl-ttrl-llm-value-head.md')})",
          f"[Jev×AP 02]({B(JEV,'main','alpha-proof/02-对象辨析-价值头与校准打分头.md')})、[03]({B(JEV,'main','alpha-proof/03-Proper评分规则与价值目标的统一语言.md')})、[Jev 08]({B(JEV,'main','jev/08-数学I-概率校准与Proper Scoring Rules.md')})"],
         ["课程 / 合成数据 / 难度",
          f"[档案 05]({B(AP,'main','05-autoformalize.md')})、[nano 03]({B(GAP,'main','03-gaps.md')})、[v1-spec 03]({B(RNUM,'master','v1-spec/03-curriculum.md')})",
          f"[Jev×AP 06]({B(JEV,'main','alpha-proof/06-合成数据-已知后验与课程生成.md')})、[plan 11]({B(RNUM,'master','plan/11-curriculum-traditional-llm.md')})"],
         ["RL / RTTT / TTRL / 自举",
          f"[档案 06]({B(AP,'main','06-main-rl.md')})、[07]({B(AP,'main','07-ttrl.md')})、[methods 03]({B(RNUM,'master','v1-spec/v1-1-training-methods/03-rl-spec.md')})、[04]({B(RNUM,'master','v1-spec/v1-1-training-methods/04-tttrl-spec.md')})",
          f"[Jev×AP 04]({B(JEV,'main','alpha-proof/04-RLCD自采样定理与引导目标.md')})、[RLVR-OPSD 资料]({T(MLT,'main','topics/RLVR-OPSD-参考资料')})"],
         ["评测 / 等计算 / 实验协议",
          f"[档案 08]({B(AP,'main','08-benchmarks.md')})、[20]({B(AP,'main','20-experiment-suite.md')})、[v1-spec 06]({B(RNUM,'master','v1-spec/06-eval.md')})",
          f"[v1-result docs]({T(RNUM,'master','v1-result/docs')})、[Jev×AP 07]({B(JEV,'main','alpha-proof/07-可迁移设计清单与实验协议.md')})"],
         ["V1-1 工具环 / agentic",
          f"[9-14-plan 01]({B(P914,'main','9-14-plan/01-architecture-interfaces.md')})、[9-14-plan 02]({B(P914,'main','9-14-plan/02-milestones-gates.md')})、[agentic README]({B(AG,'main','README.md')})",
          f"[tool driver]({T(TOOL,'main','driver')})、[贝叶斯资料]({T(MLT,'main','topics/贝叶斯概率与机器学习参考资料')})、[explain 4]({B(RNUM,'master','explain/4-alpha-proof与智能体训练是否兼容.md')})"],
         ["多智能体扩展",
          f"[MARL 1-glance]({B(MARL,'main','1-glance.md')})",
          f"[9-14 M3]({B(P914,'main','9-14-plan/modules/M3-multiagent-experts/README.md')})、[元学习资料]({T(MLT,'main','topics/元学习参考资料')})"],
         ["V2（元编程 / Eff / 塔）",
          f"[v2 spec 00]({B(RNUM,'master','explain/reap-mcts-lean-v2/00-overview.md')}) → [04]({B(RNUM,'master','explain/reap-mcts-lean-v2/04-training-and-metrics.md')})",
          f"[v2 code README]({B(RNUM,'master','reap-mcts-lean-v2-code-1/README.md')})、[explain 7]({B(RNUM,'master','explain/7-reap-v1-v2.md')})、[8]({B(RNUM,'master','explain/8-v2-math-drive.md')})"],
     ]},
    {"id": "g-status", "title": "执行状态审计（截至 2026-09-20）：哪些跑过、哪些只有文档、哪些已过时",
     "cols": ["资产", "状态", "关键证据", "位置"],
     "rows": [
         ["V1 policy_server（RTTT/快照/回滚）", "已跑通·有真实实验",
          "同一搜索树三次更新后求解；证明在独立断网 Lean 环境复验通过",
          f"[code]({B(RNUM,'master','app/policy_server.py')}) · [实验报告]({B(RNUM,'master','v1-result/docs/current/04-实际实例与验收结果.md')})"],
         ["V1 题内 TTT / 跨题继承 / 并发", "已跑通·有实验产物（20+ 项）",
          "五题链、9:1 混合、KL 回滚、副本 1.93×、快照复用等均有 JSON 证据",
          f"[证据目录]({T(RNUM,'master','v1-result/evidence/current')}) · [docs/current]({T(RNUM,'master','v1-result/docs/current')})"],
         ["V1 CPU 交付镜像（MCTS+checkProof）", "已跑通",
          "双 session smoke solved；独立 Lean 复验 exit0（仅 propext/Quot.sound）",
          f"[验收]({B(RNUM,'master','v1-result/docs/08-CPU交付镜像验收.md')}) · [validation]({T(RNUM,'master','v1-result/reproduction/validation')})"],
         ["V1 价值头（标量，共享 backbone）", "代码待验证（CPU 契约测试 17 项）",
          "测试用预计算/模拟 hidden，不加载 HF 权重；端到端价值训练在 full-v3 侧",
          f"[value_head.py]({B(RNUM,'master','app/value_head.py')}) · [tests]({B(RNUM,'master','tests/test_value_head.py')})"],
         ["V1 价值头（64 桶 full-v3）", "已跑通·有实验",
          "205,628 行训练；H1 课程 checkpoint 20 成功并发布；common-rank 0.676 vs 随机 0.493",
          f"[成功案例]({T(RNUM,'master','discussion/new_value_head_in7b_ex1')})"],
         ["V1 GPU 容器训练", "未验收",
          "原文：GPU 镜像已构建并通过本地检查，但「AMD 容器内真实推理和训练仍未验」",
          f"[docs/current/05]({B(RNUM,'master','v1-result/docs/current/05-原文与Docker逐项对照.md')})"],
         ["GRPO / TTTRL", "仅文档（未实现）",
          "全仓无 grpo 代码；实际在线目标 = search_visit_backup（访问分布 NLL + 折扣回报 MSE）",
          f"[规格 04]({B(RNUM,'master','v1-spec/v1-1-training-methods/04-tttrl-spec.md')}) · [实际目标]({B(RNUM,'master','v1-result/reproduction/code/src/gpu_runtime/search_objective.py')})"],
         ["SFT 流水线", "已过时（停用）",
          "STATUS 2026-08-26：SFT = NOT USED；主流程 = 0 长训 + on-demand RTTT",
          f"纠正版 [00-overview]({B(RNUM,'master','v1-spec/v1-1-training-on-amd-cloud/00-overview.md')})"],
         ["课程 / 教师三闸门", "仅文档；固定课程已跑通",
          "teacher+闸门未接入运行；Pell 固定 7 课课程真实成功（9 次发布）",
          f"[真实课程码]({B(RNUM,'master','v1-result/20260828-real7b-pell-success/code/cpu_runtime/curriculum_admission.py')}) · [spec]({B(RNUM,'master','v1-spec/00-overview.md')})"],
         ["效果评测（100 题 / 80%）", "仅文档",
          "原文：「100 题及 80% 效果目标未执行；本轮不追加效果对照」",
          f"[docs/current/06]({B(RNUM,'master','v1-result/docs/current/06-待办与验收范围.md')}) · [协议]({B(RNUM,'master','v1-spec/06-eval.md')})"],
         ["lean-v1（RolloutSink/Verdict）", "代码待验证",
          "纯 Lean4 标准库可独立编译；仓库无 build 回执（CPU 镜像用的是 overlay 变体）",
          f"[lean-v1/Reap/Training]({T(RNUM,'master','lean-v1/Reap/Training')})"],
         ["V2 code-1（Eff/MetaActions/Tower）", "原型（smoke 通过）",
          "lean=22 塔 / emergent=37 塔；但不是证明树（无 AND 节点、无价值头、无终局判定）",
          f"[code]({T(RNUM,'master','reap-mcts-lean-v2-code-1')}) · [lean-v2]({T(RNUM,'master','lean-v2')})"],
         ["V2 Lean gate（真实容器编译）", "已跑通（原型级）",
          "gate_lean 用容器编译判定；接受判据宽松（忽略 exit code/标记）",
          f"[gate_lean.py]({B(RNUM,'master','reap-mcts-lean-v2-code-1/v2/gate_lean.py')})"],
         ["V1-1 CPU Lean runtime（Agentic.lean）", "已跑通（编译+证据合成）",
          "主链编译通过；打印 phi = tanh(Σw) = 0.635",
          f"[Agentic.lean]({B(TOOL,'main','cpulean/Reap/Agentic.lean')})"],
         ["V1-1 GPU runtime（33 模块）", "已跑通（MI300X 真实 GPU）",
          "REAL-Prover 7B + 64 桶头 real smoke PASS 3/3（值 1.79/1.96/3.22）；模型恢复 15.2GB；online-TTT 前后哈希不同",
          f"[gpu_runtime]({T(TOOL,'main','gpu/gpu_runtime')}) · 收据在 sync（未公开）"],
         ["V1-1 工具环证据（evidence_loop）", "原型（证据后端为固定桩）",
          "真实 GPU value delta +3.2~+5.4；后端注释「后续替换为实际调用」",
          f"[evidence_loop.py]({B(TOOL,'main','driver/evidence_loop.py')}) · [v1_transports.py]({B(TOOL,'main','driver/v1_transports.py')})"],
         ["V1-1 smoke 套件", "已跑通（3 题；无单元测试/CI）",
          "mock 与真实 GPU 各 PASS 3/3；tests/ 目录为空",
          f"[smoke]({T(TOOL,'main','smoke')})"],
         ["9-14 M1–M8（V1-1 工程化）", "仅骨架代码 + 文档",
          "「接口级实现骨架」；里程碑门全部未勾选；README 提到的 tests/ 不存在",
          f"[9-14-code]({T(P914,'main','9-14-code')}) · [9-14-plan]({T(P914,'main','9-14-plan')})"],
         ["9-14-data 数据管线", "不存在",
          "目录不存在，仅在引用清单中出现",
          f"[03-references]({B(P914,'main','9-14-plan/03-references.md')})"],
         ["MARL 多智能体（下一步主线）", "仅文档（+骨架代码）",
          "1-glance 266 行数学；信用分配/种群未实现；M3 仅路由与 Jaccard 奖励骨架",
          f"[1-glance]({B(MARL,'main','1-glance.md')}) · [M3]({T(P914,'main','9-14-code/m3-multiagent')})"],
         ["nanoproof 上游", "上游有真实实验",
          "42.4/47.0/49.9/51.3% @8/32/128/256（plot）；52.7%@512 为 README 声称（非图内）",
          "[kripner/nanoproof](https://github.com/kripner/nanoproof) · [plot](https://github.com/kripner/nanoproof/blob/main/dev/combined_plots.png)"],
         ["nanoproof fork（value-head 适配）", "仅文档（无代码变更）",
          "分支只加了一个 PORTING 文档 commit；适配代码不在该仓库",
          f"[PORTING]({B(NANOF,'value-head-adapter','PORTING_REAP_VALUE_HEAD.md')})"],
         ["价值目标 / 渐进采样修正（G1/G2）", "未实现（分析已指出）",
          "search.py:677 仍整体重置 children；compute_value_target 未修",
          f"[03-gaps]({B(GAP,'main','03-gaps.md')}) · [09-code-map]({B(GAP,'main','09-code-map.md')})"],
         ["REAP 上游插件", "已跑通（上游有测试）",
          "真实 Lean tactic 插件（reap!!）；本地 fork 未改核心（Reap/Training 目录不存在）",
          "[frenzymath/reap](https://github.com/frenzymath/reap)"],
         ["RSI 公开快照", "已发布（脱敏）",
          "83 个文件；与私有版差异：不含 value-head 代码/v1-result/nanoproof",
          "[reap-rsi-public](https://github.com/wufuju2023-cell/reap-rsi-public)"],
     ]},
    {"id": "g-exp", "title": "已做过的实验台账（全部有产物；报告在 v1-result）",
     "cols": ["实验", "结论", "证据", "报告"],
     "rows": [
         ["同树三次 TTT（E）", "三次更新后同一棵树继续搜索并解出；独立断网 Lean 复验通过",
          f"[independent-wire-e.json]({B(RNUM,'master','v1-result/evidence/independent-wire-e.json')})", f"[docs/current/01]({B(RNUM,'master','v1-result/docs/current/01-题内在线TTT.md')})"],
         ["五轮 TTT 链（F）", "5 次更新可验；最终证明未通过（保留边界）；53/64 候选为空",
          f"[multi-round-ttt.json]({B(RNUM,'master','v1-result/evidence/multi-round-ttt.json')})", "（历史报告已归档，见 git 历史）"],
         ["五题多轮", "2/5 解出（Q1 三次、Q5 两次更新）；2 题耗尽预算",
          f"[multiround/]({T(RNUM,'master','v1-result/evidence/multiround')})", f"[docs/current/04]({B(RNUM,'master','v1-result/docs/current/04-实际实例与验收结果.md')})"],
         ["跨题经验继承", "3 道新题复用 1 条经验，分别更新后全部通过独立检查",
          f"[cross-problem/]({T(RNUM,'master','v1-result/evidence/current/cross-problem')})", f"[docs/current/04 §2]({B(RNUM,'master','v1-result/docs/current/04-实际实例与验收结果.md')})"],
         ["中央学习器 proof→train", "R1 证明被接受并重放；R2 发布",
          f"[central-learner/]({T(RNUM,'master','v1-result/evidence/current/central-learner')})", "docs/current/04 §3"],
         ["混合学习 9:1", "每批 9 生成 + 1 Mathlib，2 次真实更新（含完整恢复）",
          f"[mixed-learner/]({T(RNUM,'master','v1-result/evidence/current/mixed-learner')})", "docs/current/04 §4"],
         ["证明 + 反证收集", "r3 证明与反证双向接受",
          f"[collector-r3/]({T(RNUM,'master','v1-result/evidence/current/collector-r3')})", "docs/current/04 §5"],
         ["持续混合学习", "继承 R2，2 次更新，16 项检查通过",
          f"[continual-mixed/]({T(RNUM,'master','v1-result/evidence/current/continual-mixed')})", "docs/current/04 §6"],
         ["选择值刷新", "2 个未决 OR 节点更新后重估并随后解出",
          f"[selection-refresh/]({T(RNUM,'master','v1-result/evidence/current/selection-refresh')})", "docs/current/04 §7"],
         ["KL 守卫", "接受路径与全量回滚路径均在真实 7B 上验证",
          f"[kl-guard/]({T(RNUM,'master','v1-result/evidence/current/kl-guard')})", "docs/current/04 §7"],
         ["Verified replay", "11 步接受，策略 + 价值联合更新",
          f"[verified-replay/]({T(RNUM,'master','v1-result/evidence/current/verified-replay')})", "docs/current/04 §7"],
         ["快照复用", "释放约 254MB，无需重导出",
          f"[snapshot-reuse/]({T(RNUM,'master','v1-result/evidence/current/snapshot-reuse')})", "docs/current/04 §7"],
         ["双推理副本", "3 轮输出一致；中位加速 1.93×",
          f"[inference-replicas/]({T(RNUM,'master','v1-result/evidence/current/inference-replicas')})", "docs/current/04 §8"],
         ["双服务真实 Lean 搜索", "证明与反证均通过；10/10 HTTP 任务成功",
          f"[replica-collector/]({T(RNUM,'master','v1-result/evidence/current/replica-collector')})", "docs/current/04 §9"],
         ["发布版本恢复", "原运行超时后 8/8 检查通过（未重训/未重发布）",
          f"[latest-recovery-gpu/]({T(RNUM,'master','v1-result/evidence/current/latest-recovery-gpu')})", "docs/current/04 §10"],
         ["交付回归", "570/580 通过（10 skip）+ 71 工具 + 44 交付脚本测试",
          f"[local-tests.json]({B(RNUM,'master','v1-result/reproduction/validation/local-tests.json')})", "[README](%s)" % B(RNUM, "master", "README.md")],
         ["独立离线 Lean 复验", "历史证明在独立断网容器复验 exit0（仅 propext/Quot.sound）",
          f"[independent-lean/]({T(RNUM,'master','v1-result/reproduction/validation/independent-lean')})", f"[validation README]({B(RNUM,'master','v1-result/reproduction/validation/README.md')})"],
         ["Pell 真实 7B 课程", "7 课 + 原题；v0→v1（392 LoRA + 4 价值张量变更）；9 次发布",
          f"[实验包]({T(RNUM,'master','v1-result/20260828-real7b-pell-success')})", f"[README]({B(RNUM,'master','v1-result/20260828-real7b-pell-success/README.md')})"],
         ["full-v3 价值头 H1/F1", "H1 checkpoint 20 成功（step 7/15，2 次联合 TTT）；F1 用匹配随机头做因果对照",
          f"[成功案例]({T(RNUM,'master','discussion/new_value_head_in7b_ex1/02_成功案例')})", f"[当前状态]({T(RNUM,'master','discussion/new_value_head_in7b_ex1/04_当前状态与边界')})"],
         ["V1-1 真实 GPU smoke", "REAL-Prover 7B + 64 桶头 PASS 3/3（值 1.79/1.96/3.22）",
          f"[smoke]({T(TOOL,'main','smoke')})（日志未留，见 README/commit）", f"[README]({B(TOOL,'main','README.md')})"],
         ["V1-1 证据后验注入", "value delta +3.2~+5.4；phi=0.635",
          f"[evidence_loop.py]({B(TOOL,'main','driver/evidence_loop.py')})（无日志）", f"[README]({B(TOOL,'main','README.md')})"],
         ["V2 smoke 运行", "lean 塔 22 / emergent 塔 37（无持久日志）",
          f"[code README]({B(RNUM,'master','reap-mcts-lean-v2-code-1/README.md')})", f"[mine.py]({B(RNUM,'master','reap-mcts-lean-v2-code-1/v2/mine.py')})"],
         ["common-rank 评测（价值头）", "full 0.6756 [0.6449, 0.7064] vs 随机 0.4927（453 族/2318 对/2104 样本）",
          "收据在 sync 工作区（未公开）", "—"],
     ]},
    {"id": "g-old", "title": "已过时 / 已被纠正的文档（不要按旧文实现；用「纠正版」列）",
     "cols": ["旧文档（过时）", "问题", "纠正版 / 最新事实"],
     "rows": [
         ["v1-spec/v1-1-training-methods/02-sft-spec.md（2026-09-20 已从仓库剔除）" + f"、[04-training §4.1]({B(RNUM,'master','v1-spec/04-training.md')})、[methods 00]({B(RNUM,'master','v1-spec/v1-1-training-methods/00-index.md')})",
          "把 SFT 当主线阶段 A",
          f"[SFT = NOT USED 状态]({B(RNUM,'master','v1-spec/v1-1-training-on-amd-cloud/00-overview.md')})（2026-08-26）"],
         [f"[plan/00]({B(RNUM,'master','plan/00-index.md')})、[plan/05]({B(RNUM,'master','plan/05-rl-param-update.md')})、[plan/11]({B(RNUM,'master','plan/11-curriculum-traditional-llm.md')})",
          "把 GRPO/PPO 当主训练回路",
          f"[docs/current/05]({B(RNUM,'master','v1-result/docs/current/05-原文与Docker逐项对照.md')})：GRPO 不属于本轮；实际目标 [search_objective.py]({B(RNUM,'master','v1-result/reproduction/code/src/gpu_runtime/search_objective.py')})"],
         [f"[v1-spec/01 §1.2]({B(RNUM,'master','v1-spec/01-policy-value.md')})",
          "价值头输入维度写死 4096；提到 LLM-JSON prefit",
          f"[VALUE_HEAD.md]({B(RNUM,'master','app/VALUE_HEAD.md')})：维度动态读取（实际 3584）"],
         ["v1-result/docs 01–10（2026-08-27 版；2026-09-20 已从仓库剔除，仅存 git 历史）",
          "历史报告，多处「尚未接通」已实现",
          f"[docs/current 00–06]({T(RNUM,'master','v1-result/docs/current')})"],
         [f"[02-rttt.md §2.4]({B(RNUM,'master','v1-spec/v1-1-training-on-amd-cloud/02-rttt.md')})",
          "「V1 先不接 Lean full MCTS」",
          f"[docs/current/04]({B(RNUM,'master','v1-result/docs/current/04-实际实例与验收结果.md')})：已接真实 Lean 搜索"],
         [f"[v1-spec/01 §1.1]({B(RNUM,'master','v1-spec/01-policy-value.md')})",
          "LoRA r32/α64/dropout 0.05",
          f"实际 r16/α32/0.02（[Pell 系统说明]({B(RNUM,'master','v1-result/20260828-real7b-pell-success/02-system-and-training.md')}) + [policy_server.py]({B(RNUM,'master','app/policy_server.py')})）"],
         [f"[docker/README.md]({B(RNUM,'master','docker/README.md')})",
          "「镜像/CI 就绪」的设计期说法",
          f"[docs/current/05/06]({T(RNUM,'master','v1-result/docs/current')})：仅本地镜像；容器训练未验收"],
         [f"[code-1 README 的 Lean 构建命令]({B(RNUM,'master','reap-mcts-lean-v2-code-1/README.md')})",
          "命令被省略（…）且 code-1/lean-v2 无 lakefile",
          f"[lean-v2/]({T(RNUM,'master','lean-v2')}) 为可编译版本（v2proj）"],
         [f"[new-v2-gather-source-code/README]({B(RNUM,'master','new-v2-gather-source-code/README.md')})",
          "「no-miner 暂不接任务挖掘器」",
          f"[mine.py]({B(RNUM,'master','reap-mcts-lean-v2-code-1/v2/mine.py')}) 已实现（commit f72c270）"],
         ["[nanoproof/TODO.md](https://github.com/kripner/nanoproof/blob/main/TODO.md)",
          "指向已删除的 rl_server.py；replay 规模与实际不符",
          f"[03-gaps.md]({B(GAP,'main','03-gaps.md')}) + [09-code-map.md]({B(GAP,'main','09-code-map.md')})"],
         ["[LL-00](%s)" % B(LEAN, "main", "LL-00-README-plan.md"),
          "头部写 Status: PLAN（未写）",
          f"[LL-01]({B(LEAN,'main','LL-01-lean4-repo-and-pipeline.md')})…[LL-12]({B(LEAN,'main','LL-12-widgets-rpc-trythis.md')}) 已成文"],
         ["[hsy 03_基座与公开工作（旧版）](%s)" % B(HSY, "main", "0916/03_基座与公开工作.md"),
          "旧版本，作者标注供对照",
          f"[03_alphaproof_public_models（更新版）]({B(HSY,'main','0916/03_alphaproof_public_models.md')})"],
         ["[control/01](%s)" % B(RNUM, "master", "v1-spec/v1-1-training-example/control/01-ssh-and-channels.md"),
          "网关 /lab?appId=MAAS 通道已停用（2026-08-26）",
          "同文档的 workspace 流程 + commit a32d40c"],
         [f"[档案 06 §4]({B(AP,'main','06-main-rl.md')})",
          "AdamW 超参为历史猜测",
          f"[pseudocode.py]({B(APM,'main','pseudocode.py')})（optax.adam）+ [mcts 13]({B(MCTS,'main','13-gradient-descent-and-optimizers.md')})"],
         [f"[档案 13/14]({B(AP,'main','13-mcts-theory.md')})",
          "PUCT/MCTS 第一版推导",
          f"[mcts 6]({B(MCTS,'main','6-alpha-proof-mcts-rl.md')})、[8-6]({B(MCTS,'main','8-6-q-transform-reason-1.md')})、[explain/1-13]({B(AP,'main','explain/1-13-mcts-puct.md')})"],
     ]},
    {"id": "g-ideas", "title": "数学想法 → 文档位置 → 代码实现（全部为 GitHub 具体位置）",
     "cols": ["想法", "最新文档", "代码实现", "状态"],
     "rows": [
         ["价值 d(s) = 期望剩余步数（AND 取 max，OR 取期望）", f"[档案 00/03]({B(AP,'main','03-search.md')})", "[pseudocode.py](%s)；Reap 价值端点读取见 [reap-source 05](%s)" % (B(APM, "main", "pseudocode.py"), B(REAPS, "main", "05-policy-value-premise.md")), "定义明确；实现=官方伪代码（参考）"],
         ["分类价值头（距离桶分布 + 期望解码）", f"[档案 02 §3]({B(AP,'main','02-proof-network.md')})", "[nano tokenizer/inference](https://github.com/kripner/nanoproof/blob/main/nanoproof/inference.py)；V1 标量头 [value_head.py](%s)；64 桶训练在 [full-v3](%s)" % (B(RNUM, "master", "app/value_head.py"), T(RNUM, "master", "discussion/new_value_head_in7b_ex1")), "V1 标量已实现；桶分布见 nano/full-v3"],
         ["Q 变换 γ^{d-1}（尺度校准）", f"[档案 03 §1]({B(AP,'main','03-search.md')})、[mcts 8-6]({B(MCTS,'main','8-6-q-transform-reason-1.md')})", f"[search_objective.py]({B(RNUM,'master','v1-result/reproduction/code/src/gpu_runtime/search_objective.py')})（value_to_distance / distance_to_value）", "V1 已实现"],
         ["PUCT 选择（探索系数 c(s)）", f"[档案 14]({B(AP,'main','14-puct-and-temperature.md')})、[mcts 6]({B(MCTS,'main','6-alpha-proof-mcts-rl.md')})", "[Reap Tactic/TreeSearch.lean](https://github.com/frenzymath/reap/blob/main/Reap/Tactic/TreeSearch.lean)；[nano search.py](https://github.com/kripner/nanoproof/blob/main/nanoproof/search.py)", "上游已实现"],
         ["AND/OR 节点语义（子目标独立、最坏分支）", f"[档案 01/03]({B(AP,'main','01-lean-env.md')})", "[Reap Tactic/TreeSearch.lean](https://github.com/frenzymath/reap/blob/main/Reap/Tactic/TreeSearch.lean)", "上游已实现"],
         ["渐进采样（n ≤ C·N^α 时补采样）", f"[档案 03 §3]({B(AP,'main','03-search.md')})", "[Reap TreeSearch.lean](https://github.com/frenzymath/reap/blob/main/Reap/Tactic/TreeSearch.lean)；nano [search.py:677](https://github.com/kripner/nanoproof/blob/main/nanoproof/search.py)", "上游实现；nano 有 bug（待修）"],
         ["Expert iteration（只学验证成功轨迹）", f"[档案 12/16]({B(AP,'main','12-rl-math.md')})", "[REAL-Prover](https://github.com/frenzymath/REAL-Prover)（外部训练）", "上游已实现"],
         ["matchmaker 自适应预算", f"[档案 06 §2]({B(AP,'main','06-main-rl.md')})", "[pseudocode.py Matchmaker](%s)；nano rl.py" % B(APM, "main", "pseudocode.py"), "参考实现"],
         ["TTRL 变体生成 + 演化课程", f"[档案 07/18]({B(AP,'main','07-ttrl.md')})", "无公开实现", "计划：" + f"[methods 04]({B(RNUM,'master','v1-spec/v1-1-training-methods/04-tttrl-spec.md')})"],
         ["Autoformalization（微调 + STaR + 等价闸门）", f"[档案 05]({B(AP,'main','05-autoformalize.md')})", "无", "论文参考"],
         ["反证（disproof 特殊动作）", f"[档案 06/17]({B(AP,'main','06-main-rl.md')})", "[pseudocode.py](%s)" % B(APM, "main", "pseudocode.py"), "参考"],
         ["状态去重 / 换位（canonical key）", f"[reap-source 04/06]({B(REAPS,'main','04-proof-state-step.md')})", "[Reap Tactic/State.lean](https://github.com/frenzymath/reap/blob/main/Reap/Tactic/State.lean)", "上游已实现"],
         ["价值校准 / proper scoring（NLL/CRPS/PIT/VE）", f"[Jev×AP 03]({B(JEV,'main','alpha-proof/03-Proper评分规则与价值目标的统一语言.md')})", "无（D1/D2 提案）", "待实现（支线）"],
         ["Jev 校准决策头（choice/score/noul）", f"[Jev×AP 02]({B(JEV,'main','alpha-proof/02-对象辨析-价值头与校准打分头.md')})、[Jev 03]({B(JEV,'main','jev/03-Jev架构与API机制.md')})", "外部复刻（open-jev / jevlike，见 Jev 05/07）", "参考（支线）"],
         ["RLCD：自采样会奖励熵（方向由分数决定）", f"[Jev×AP 04]({B(JEV,'main','alpha-proof/04-RLCD自采样定理与引导目标.md')})", "无", "定理（训练回路规则）"],
         ["TTT / RTTT / TTTRL（用即学 + 快照回滚）", f"[plan 09]({B(RNUM,'master','plan/09-test-time-training.md')})、[methods 04]({B(RNUM,'master','v1-spec/v1-1-training-methods/04-tttrl-spec.md')})", f"[policy_server.py]({B(RNUM,'master','app/policy_server.py')}) + [online_ttt.py]({B(RNUM,'master','v1-result/reproduction/code/src/cpu_runtime/online_ttt.py')})", "已跑通（有实验）"],
         ["GRPO（组归一化策略梯度）", f"[档案 16]({B(AP,'main','16-llm-posttraining-choices.md')})、[plan 05]({B(RNUM,'master','plan/05-rl-param-update.md')})", f"无（[9-14 m5]({B(P914,'main','9-14-code/m5-trainer-lora/lora_trainer.py')}) 显式 NotImplementedError）", "未实现"],
         ["LoRA / QLoRA 训练", f"[v1-spec 01 §1.1]({B(RNUM,'master','v1-spec/01-policy-value.md')})、[2-9-14-Q]({B(P914,'main','2-9-14-Q.md')})", "[policy_server.py](%s)；9-14 [m5](%s)/[m6](%s)" % (B(RNUM, "master", "app/policy_server.py"), B(P914, "main", "9-14-code/m5-trainer-lora/lora_trainer.py"), B(P914, "main", "9-14-code/m6-trainer-qlora/qlora_trainer.py")), "LoRA 已跑通；QLoRA 阻塞（ROCm）"],
         ["Eff 通道（V2：类型化世界效应）", f"[v2 spec 01]({B(RNUM,'master','explain/reap-mcts-lean-v2/01-eff-channel.md')})", f"[eff_registry.py]({B(RNUM,'master','reap-mcts-lean-v2-code-1/v2/eff_registry.py')}) + [Effect.lean]({B(RNUM,'master','lean-v2/src/v2/Effect.lean')})", "原型（2 个玩具效应）"],
         ["塔上升（V2：验证入库 ⇔ 语言塔上升）", f"[v2 spec 03]({B(RNUM,'master','explain/reap-mcts-lean-v2/03-tower.md')})", f"[tower.py]({B(RNUM,'master','reap-mcts-lean-v2-code-1/v2/tower.py')}) + [MCTS.lean]({B(RNUM,'master','lean-v2/src/v2/MCTS.lean')}) + [gate_lean.py]({B(RNUM,'master','reap-mcts-lean-v2-code-1/v2/gate_lean.py')})", "原型（真实容器 gate）"],
         ["联合策略 π_joint / 信用分配 / 种群（MARL）", f"[1-glance]({B(MARL,'main','1-glance.md')})", f"[m3 骨架]({T(P914,'main','9-14-code/m3-multiagent')})（路由 + Jaccard 奖励）", "仅文档 + 骨架（下一步主线）"],
         ["工具环 Bayes 证据（φ = tanh(Σw)）", f"[9-14 00 §3]({B(P914,'main','9-14-plan/00-math-theory.md')})、[tool README]({B(TOOL,'main','README.md')})", f"[Agentic.lean]({B(TOOL,'main','cpulean/Reap/Agentic.lean')}) + [evidence_loop.py]({B(TOOL,'main','driver/evidence_loop.py')})", "已跑通（证据后端仍为桩）"],
     ]},
]

MODULES = [
    {
        "id": "m1", "title": "模块一 · 项目（主线 V1 / V1-1，扩展 MARL，实验性 V2）",
        "parts": [
            {
                "id": "p1", "title": "Part 1 · AlphaProof 源头与官方资料（最高优先级）",
                "lead": "先读分析档案（公式级重构），再回原论文与官方伪代码；Nexus 是 2026 年 Agent 方向的后续，hsy 材料用于交叉核查。",
                "items": [
                    C("c_dossier", "分析档案：alpha-proof-original-math-version ★",
                      "21 篇数学化重构：公式级讲解 + 重建路线 + 实验协议；V1/V1-1 的语义基准。",
                      tags=["核心", "优先"],
                      paths=[("wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup")],
                      links=[("github", T(AP, "main"), "GitHub 仓库")],
                      quick=[("00 总览", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/00-overview.md"),
                             ("01 Lean 环境", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/01-lean-env.md"),
                             ("02 网络/价值头", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/02-proof-network.md"),
                             ("03 搜索/PUCT", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/03-search.md"),
                             ("06 主 RL", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/06-main-rl.md"),
                             ("09 重建计划", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/09-reconstruction-plan.md"),
                             ("20 实验套件", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/20-experiment-suite.md")],
                      reads="学习 00→01→03→02→04→06→05→07→08；重建 09→19→20；对照 08+20"),
                    C("c_nature", "原论文与官方材料",
                      "Nature 2025 论文（本地全文副本）+ 官方补充材料 pseudocode.py / supplementary（无独立官方仓库）。",
                      tags=["源头", "官方"],
                      paths=[("wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/refs-alpha-proof-paper-nature-2025.md"),
                             ("wsl", "/home/zhai/project/alphaproof-official-materials")],
                      links=[("doi", "https://doi.org/10.1038/s41586-025-09833-y", "doi 10.1038/s41586-025-09833-y"),
                             ("github", T(APM, "main"), "官方材料仓库"),
                             ("web", "https://www.nature.com/articles/s41586-025-09833-y", "Nature 页面")]),
                    C("c_nexus", "AlphaProof Nexus（2026 · Agent 方向）",
                      "arXiv:2605.22763；Gemini+Lean 的数学研究 Agent，证明 9 个 Erdős 问题与 44 个 OEIS 猜想。",
                      tags=["2026", "Agent"],
                      paths=[("wsl", "/home/zhai/project/alphaproof-nexus-results")],
                      links=[("arxiv", "https://arxiv.org/abs/2605.22763", "arXiv:2605.22763"),
                             ("github", "https://github.com/google-deepmind/alphaproof-nexus-results", "官方 repo")],
                      reads="想了解 Agent 化证明的方向时读；与 V1-1 的工具环/长程任务相关"),
                    C("c_hsy", "hsy AlphaProof 分析 0916（交叉核查）",
                      "11 篇：原版机制 / TTRL 与并发 / 公开模型 / nano 源码核查 / Nexus 课程 / Matchmaker。",
                      tags=["参考"],
                      paths=[("remote", "/home/a/文档/hsy-alphaproof-public/0916")],
                      links=[("github", T(HSY, "main", "0916"), "GitHub · 0916/")],
                      quick=[("00 总览", "remote", "/home/a/文档/hsy-alphaproof-public/0916/00_总览.md"),
                             ("04 nano 核查", "remote", "/home/a/文档/hsy-alphaproof-public/0916/04_nano源码核查.md"),
                             ("09 Matchmaker", "remote", "/home/a/文档/hsy-alphaproof-public/0916/09_Matchmaker_and_nanoproof.md")]),
                ],
            },
            {
                "id": "p2", "title": "Part 2 · NanoProof（开源复现基线：读差距，定 V1 目标）",
                "lead": "不要只读 README：价值目标实现（experience_collection.py:771-793）与渐进采样（search.py:677）是两处已定位的真缺陷，直接看 03-gaps 与 09-code-map。",
                "items": [
                    C("c_nano_upstream", "上游：kripner/nanoproof",
                      "端到端开源 AlphaProof 风格 prover（~1.03B；MiniF2F-valid 52.7%@512）。",
                      tags=["上游"],
                      links=[("github", NANO, "kripner/nanoproof")]),
                    C("c_nano_fork", "你的 fork：nanoproof-value-head",
                      "value-head-adapter 分支；含官方 pseudocode.py 副本与 PORTING_REAP_VALUE_HEAD.md。",
                      tags=["fork"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/nanoproof")],
                      links=[("github", T(NANOF, "main"), "GitHub fork"),
                             ("github", B(NANOF, "value-head-adapter", "PORTING_REAP_VALUE_HEAD.md"), "PORTING_REAP_VALUE_HEAD.md")],
                      quick=[("pseudocode.py", "remote", "/mnt/gloway/projects/reap-new-update-model/nanoproof/pseudocode.py")]),
                    C("c_nano_analysis", "分析：gap-advance-plan（G/A/E 台账）★",
                      "差距 G1-G20、超越 A1-A11、路线 P0-P4、实验 E1-E20、代码地图与分数板。",
                      tags=["核心"],
                      paths=[("wsl", "/home/zhai/project/gap-advance-plan-of-nano-proof-v1-m1")],
                      links=[("github", T(GAP, "main"), "GitHub 仓库")],
                      quick=[("00 总览", "wsl", "/home/zhai/project/gap-advance-plan-of-nano-proof-v1-m1/00-overview.md"),
                             ("03 差距", "wsl", "/home/zhai/project/gap-advance-plan-of-nano-proof-v1-m1/03-gaps.md"),
                             ("05 计划", "wsl", "/home/zhai/project/gap-advance-plan-of-nano-proof-v1-m1/05-future-plan.md"),
                             ("09 代码地图", "wsl", "/home/zhai/project/gap-advance-plan-of-nano-proof-v1-m1/09-code-map.md"),
                             ("10 分数板", "wsl", "/home/zhai/project/gap-advance-plan-of-nano-proof-v1-m1/10-benchmark-scoreboard.md")],
                      reads="00→01→02→03→04→05；动手前 09，复查数字 10"),
                    C("c_reap_gap", "REAP × AlphaProof 差距补充",
                      "00-index→04 逐项对照→06 路线；与 nano 分析互补。",
                      tags=["参考"],
                      paths=[("remote", "/mnt/gloway/projects/reap-gap-advance-alpha-proof")],
                      links=[("github", T(RGAP, "main"), "GitHub 仓库")],
                      quick=[("00 索引", "remote", "/mnt/gloway/projects/reap-gap-advance-alpha-proof/00-index.md"),
                             ("04 对照", "remote", "/mnt/gloway/projects/reap-gap-advance-alpha-proof/04-reap-vs-alphaproof.md")]),
                ],
            },
            {
                "id": "p3", "title": "Part 3 · REAP（V1 的代码基座）",
                "lead": "源码精读按 01→02→04→06 走；06-mcts-core 是唯一必须逐行读的模块（PUCT/回传/证明提取都在里面）。",
                "items": [
                    C("c_reap_upstream", "上游：frenzymath/reap",
                      "Lean 内神经证明搜索：policy/value/premise 三端点 + MCTS（reap!! / reapMCTS）。",
                      tags=["上游"],
                      links=[("github", REAP, "frenzymath/reap"),
                             ("github", "https://github.com/IQuestLab/reap", "IQuestLab/reap")]),
                    C("c_reap_local", "工作区（私有 fork）",
                      "Reap/ 源码 + V1/V2 改动；V1-1 cpulean 与容器镜像的来源。",
                      tags=["工作区"],
                      paths=[("wsl", "/home/zhai/project/reap")],
                      links=[("github", T(REAPP, "main"), "GitHub（私有）")]),
                    C("c_reap_source", "源码精读 8 篇 ★",
                      "Lean4 入门 → 架构 → 树库 → Step 验证 → Generator → MCTS 内核 → widget → 测试。",
                      tags=["核心"],
                      paths=[("wsl", "/home/zhai/project/reap/reap-source-code-explain")],
                      links=[("github", T(REAPS, "main"), "GitHub 仓库")],
                      quick=[("00 INDEX", "wsl", "/home/zhai/project/reap/reap-source-code-explain/00-INDEX.md"),
                             ("01 Lean4 入门", "wsl", "/home/zhai/project/reap/reap-source-code-explain/01-lean4-from-zero.md"),
                             ("02 架构", "wsl", "/home/zhai/project/reap/reap-source-code-explain/02-architecture-overview.md"),
                             ("04 State/Step", "wsl", "/home/zhai/project/reap/reap-source-code-explain/04-proof-state-step.md"),
                             ("06 MCTS 内核", "wsl", "/home/zhai/project/reap/reap-source-code-explain/06-mcts-core.md")],
                      reads="01→02→03→04→05→06→07→08；06 必精读"),
                    C("c_real_prover", "REAL-Prover（7B 基座模型）",
                      "arXiv:2505.20613；Qwen2.5-Math-7B 微调，Lean step prover。",
                      tags=["模型"],
                      links=[("arxiv", "https://arxiv.org/abs/2505.20613", "arXiv:2505.20613"),
                             ("github", "https://github.com/frenzymath/REAL-Prover", "GitHub"),
                             ("hf", "https://huggingface.co/FrenzyMath/REAL-Prover", "HF 权重")]),
                ],
            },
            {
                "id": "p4", "title": "Part 4 · V1 主线（REAL-Prover 7B + 价值头 + on-demand RTTT）",
                "lead": "按「规格 → 代码 → 实验」三段读：先 v1-spec 00/01/02/04，再 app/ 与 methods，最后 v1-result 复现。开发落点见导航表 M2–M5。",
                "items": [
                    C("c_v1_spec", "V1 规格：v1-spec（00-07 + 1-plan）★",
                      "0 长训 + 用即学（on-demand RTTT）；policy/value/MCTS/课程/训练/评测/runbook。",
                      tags=["主线", "核心"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/v1-spec"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/v1-spec")],
                      links=[("github", T(RNUM, "master", "v1-spec"), "GitHub · v1-spec/"),
                             ("github", T(RSI, "master", "v1-spec"), "公开镜像 rsi-public")],
                      quick=[("00 系统综述", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/00-overview.md"),
                             ("01 Policy&Value", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/01-policy-value.md"),
                             ("02 MCTS&验证器", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/02-mcts-verifier.md"),
                             ("04 训练", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/04-training.md"),
                             ("05 基础设施", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/05-infra.md"),
                             ("07 Runbook", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/07-runbook.md")],
                      reads="00→01→02→03→04→05→07（跑起来直接看 07）"),
                    C("c_v1_plan", "V1 计划：plan/（00-12）",
                      "研究计划：动机、架构、MCTS 环境、数据、RL 参数更新、评测、路线图；TTT/RSI/课程/双模型。",
                      tags=["设计"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/plan"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/plan")],
                      links=[("github", T(RNUM, "master", "plan"), "GitHub · plan/")],
                      quick=[("00 索引", "wsl", "/home/zhai/project/reap/new-update-model/plan/00-index.md"),
                             ("01 动机", "wsl", "/home/zhai/project/reap/new-update-model/plan/01-motivation.md"),
                             ("05 RL 更新", "wsl", "/home/zhai/project/reap/new-update-model/plan/05-rl-param-update.md"),
                             ("09 TTT", "wsl", "/home/zhai/project/reap/new-update-model/plan/09-test-time-training.md"),
                             ("12 双模型", "wsl", "/home/zhai/project/reap/new-update-model/plan/12-two-model-architecture.md")],
                      reads="00→01→02→03→05→08→09→12"),
                    C("c_v1_explain", "深度分析：explain/（1-13）",
                      "价值头作用、难题进步、harness、AlphaProof×Agent、元编程、V1/V2、上下文管理。",
                      tags=["分析"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/explain"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/explain")],
                      links=[("github", T(RNUM, "master", "explain"), "GitHub · explain/"),
                             ("github", T(RNUM, "master", "explain/new-deep-explain-v2"), "new-deep-explain-v2（价值头专题）")],
                      quick=[("1 价值头的作用", "wsl", "/home/zhai/project/reap/new-update-model/explain/1-价值头的作用.md"),
                             ("7 Reap V1/V2", "wsl", "/home/zhai/project/reap/new-update-model/explain/7-reap-v1-v2.md"),
                             ("10 MCTS 用途", "wsl", "/home/zhai/project/reap/new-update-model/explain/10-mcts-usage-and-alternatives.md"),
                             ("11 self-play vs TTT", "wsl", "/home/zhai/project/reap/new-update-model/explain/11-selfplay-alpha-zero-vs-reap-ttt.md")]),
                    C("c_v1_cpu", "V1 CPU 端代码（全量归集）",
                      "reap-upstream（原样）+ reap-training（Verdict / RolloutSink）+ python-driver（编排）。",
                      tags=["代码"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/new-v1-gather-source-code-cpu")],
                      links=[("github", T(RNUM, "master", "new-v1-gather-source-code-cpu"), "GitHub · 目录"),
                             ("github", B(RNUM, "master", "new-v1-gather-source-code-cpu/README.md"), "README")],
                      quick=[("RolloutSink/", "remote", "/mnt/gloway/projects/reap-new-update-model/new-v1-gather-source-code-cpu/reap-training/Reap"),
                             ("python-driver/", "remote", "/mnt/gloway/projects/reap-new-update-model/new-v1-gather-source-code-cpu/python-driver")]),
                    C("c_v1_gpu", "V1 GPU 端代码（app/）",
                      "policy_server（RTTT / TTTRT）/ value_head / train_value_head / rttt_demo / v1_run / v1_sink。",
                      tags=["代码"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/app"),
                             ("wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-example/scripts")],
                      links=[("github", T(RNUM, "master", "app"), "GitHub · app/"),
                             ("github", B(RNUM, "master", "app/policy_server.py"), "policy_server.py"),
                             ("github", B(RNUM, "master", "app/value_head.py"), "value_head.py"),
                             ("github", B(RNUM, "master", "app/train_value_head.py"), "train_value_head.py")],
                      quick=[("VALUE_HEAD.md", "remote", "/mnt/gloway/projects/reap-new-update-model/app/VALUE_HEAD.md"),
                             ("rttt_demo.py", "remote", "/mnt/gloway/projects/reap-new-update-model/app/rttt_demo.py"),
                             ("v1_run.py", "remote", "/mnt/gloway/projects/reap-new-update-model/app/v1_run.py")]),
                    C("c_v1_methods", "训练方法规格：v1-1-training-methods（00-06）",
                      "数据 / SFT（已停用，保险丝）/ GRPO / TTTRL / 值头训练 / 组合调度与超参清单。",
                      tags=["规格"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-methods"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/v1-spec/v1-1-training-methods")],
                      links=[("github", T(RNUM, "master", "v1-spec/v1-1-training-methods"), "GitHub · 目录")],
                      quick=[("00 索引", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-methods/00-index.md"),
                             ("01 数据", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-methods/01-data-spec.md"),
                             ("03 GRPO", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-methods/03-rl-spec.md"),
                             ("04 TTTRL", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-methods/04-tttrl-spec.md"),
                             ("06 超参目录", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-methods/06-catalog.md")]),
                    C("c_v1_amd", "AMD 云与环境规格",
                      "v1-1-training-on-amd-cloud（W7900×4 / ROCm / RTTT）+ environment-spec（环境复用与状态布局）。",
                      tags=["基础设施"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-on-amd-cloud"),
                             ("wsl", "/home/zhai/project/environment-spec"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/environment-spec")],
                      links=[("github", T(RNUM, "master", "v1-spec/v1-1-training-on-amd-cloud"), "GitHub · AMD 云"),
                             ("github", T(RNUM, "master", "environment-spec"), "GitHub · environment-spec")],
                      quick=[("00 总览", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-on-amd-cloud/00-overview.md"),
                             ("02 RTTT", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-on-amd-cloud/02-rttt.md")]),
                    C("c_v1_example", "环境/控制面示例：v1-1-training-example",
                      "实例环境、SSH 与 opencli 自动化、env-sync、脚本与评测集。",
                      tags=["基础设施"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-example"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/v1-spec/v1-1-training-example")],
                      links=[("github", T(RNUM, "master", "v1-spec/v1-1-training-example"), "GitHub · 目录")],
                      quick=[("README", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-example/README.md"),
                             ("control 00", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-example/control/00-index.md")]),
                    C("c_v1_result", "V1 实验记录：v1-result ★（已跑通·有实验）",
                      "2026-08-28 Pell 实验：题内 TTT、跨题经验、并发调度；证据 JSON、复现文档、CPU/GPU runtime。",
                      tags=["实验", "核心", "已跑通", "有实验"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/v1-result")],
                      links=[("github", T(RNUM, "master", "v1-result"), "GitHub · v1-result/")],
                      quick=[("README", "remote", "/mnt/gloway/projects/reap-new-update-model/v1-result/README.md"),
                             ("current/00 地图", "remote", "/mnt/gloway/projects/reap-new-update-model/v1-result/docs/current/00-总设计与阅读地图.md"),
                             ("current/01 题内 TTT", "remote", "/mnt/gloway/projects/reap-new-update-model/v1-result/docs/current/01-题内在线TTT.md"),
                             ("current/04 结果", "remote", "/mnt/gloway/projects/reap-new-update-model/v1-result/docs/current/04-实际实例与验收结果.md"),
                             ("reproduction/01", "remote", "/mnt/gloway/projects/reap-new-update-model/v1-result/reproduction/01-单题TTT.md")],
                      reads="README→docs/current/00→01→04；复现 reproduction/00→04"),
                    C("c_v1_value_head", "价值头：语义 + 实现 + 权重 ★（有实验）",
                      "共享 REAL-Prover backbone 的标量头（H→256→1, tanh, V∈[-1,1]）；scalar/distance 两种输出模式。",
                      tags=["模型", "核心", "有实验"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/app/VALUE_HEAD.md"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/discussion")],
                      links=[("github", B(RNUM, "master", "app/VALUE_HEAD.md"), "VALUE_HEAD.md"),
                             ("github", T(RNUM, "master", "discussion/alphaproof-value-head"), "value-head 讨论"),
                             ("hf", "https://huggingface.co/WufuJu/reap-value-head-v1-scaling", "HF: reap-value-head-v1-scaling")],
                      quick=[("讨论 README", "remote", "/mnt/gloway/projects/reap-new-update-model/discussion/alphaproof-value-head/README.md"),
                             ("搜索_Value与TTT", "remote", "/mnt/gloway/projects/reap-new-update-model/discussion/alphaproof-value-head/07_AlphaProof从零到完整机制_搜索_Value与TTT.md")],
                      reads="档案 02+12 先定语义（期望步数，不是百分比）；再 VALUE_HEAD.md"),
                    C("c_v1_models", "模型与基座（HF）",
                      "基座 REAL-Prover（FrenzyMath）；你的 HF 主页：价值头 v1-scaling、alpha-proof-open-v1、v1-1-fullv3-artifact、step-prover-critic。",
                      tags=["模型"],
                      links=[("hf", "https://huggingface.co/WufuJu", "HF 主页 WufuJu"),
                             ("hf", "https://huggingface.co/WufuJu/reap-value-head-v1-scaling", "价值头模型"),
                             ("hf", "https://huggingface.co/FrenzyMath/REAL-Prover", "基座 REAL-Prover")]),
                    C("c_v1_bench", "评测基准仓库",
                      "formal-imo（258 题）与 miniF2F 的 Lean 形式化（Lean 4.27）。",
                      tags=["评测"],
                      paths=[("wsl", "/home/zhai/project/formal-imo"), ("wsl", "/home/zhai/project/miniF2F")],
                      links=[("github", "https://github.com/google-deepmind/formal-imo", "google-deepmind/formal-imo"),
                             ("github", "https://github.com/google-deepmind/miniF2F", "google-deepmind/miniF2F")]),
                    C("c_opd", "步骤级 OPD 改良设计（新设计）",
                      "把 OPD 从 token 级改为 state→tactic 步骤级：KL 分解与不变性定理、课程调度闭式解、"
                      "样本效率下界与教师成本、实现规范与可运行代码（10 篇 + code/）。",
                      tags=["设计", "主线"],
                      paths=[("remote", "/home/a/文档/opd-alpha-proof-steps-version-not-token")],
                      quick=[("00 总览", "remote", "/home/a/文档/opd-alpha-proof-steps-version-not-token/00-总览与导读.md"),
                             ("03 形式化与定理", "remote", "/home/a/文档/opd-alpha-proof-steps-version-not-token/03-步骤级OPD-形式化与不变性定理.md"),
                             ("04 搜索集成", "remote", "/home/a/文档/opd-alpha-proof-steps-version-not-token/04-教师作为搜索先验与价值指导.md"),
                             ("05 课程调度", "remote", "/home/a/文档/opd-alpha-proof-steps-version-not-token/05-课程与混合日程.md"),
                             ("06 样本效率", "remote", "/home/a/文档/opd-alpha-proof-steps-version-not-token/06-样本效率与教师成本模型.md"),
                             ("07 实现规范", "remote", "/home/a/文档/opd-alpha-proof-steps-version-not-token/07-实现规范-数据-接口与日志.md"),
                             ("code README", "remote", "/home/a/文档/opd-alpha-proof-steps-version-not-token/code/README.md")],
                      reads="00→01→03→05；实现看 07 与 code/；实验看 08"),
                ],
            },
            {
                "id": "p5", "title": "Part 5 · V1-1 主线（agentic-tool）+ 多智能体扩展（下一步主线）",
                "lead": "V1-1 = CPU Lean 运行时 + GPU Python 桥 + 工具环证据，已在 MI300X 真实 GPU 上 smoke 3/3；"
                        "多智能体（MARL）已有完整数学形式化（1-glance），是下一步主线，代码目前只有 M3 骨架。",
                "items": [
                    C("c_agentic_repo", "仓库：reap-agentic-v1-1 ★",
                      "Lean CPU（本地 mathlib）+ GPU 传输桥；agent 工具环作为 Bayes 先验/后验证据。",
                      tags=["主线", "代码"],
                      paths=[("remote", "/mnt/gloway/projects/reap-agentic-v1-1")],
                      links=[("github", T(AG, "main"), "GitHub 仓库"),
                             ("github", B(AG, "main", "README.md"), "README")],
                      quick=[("cpulean/", "remote", "/mnt/gloway/projects/reap-agentic-v1-1/cpulean"),
                             ("driver/", "remote", "/mnt/gloway/projects/reap-agentic-v1-1/driver"),
                             ("smoke/", "remote", "/mnt/gloway/projects/reap-agentic-v1-1/smoke")]),
                    C("c_agentic_tool", "仓库：v1-1-agentic-tool ★（MI300X 已跑通）",
                      "CPU runtime（Main.lean）+ gpu_runtime（33 模块：learner/search/verified/snapshot）+ 证据循环。",
                      tags=["主线", "代码", "已跑通"],
                      paths=[("remote", "/mnt/gloway/projects/v1-1-agentic-tool")],
                      links=[("github", T(TOOL, "main"), "GitHub 仓库"),
                             ("github", B(TOOL, "main", "README.md"), "README"),
                             ("github", B(TOOL, "main", "cpulean/Main.lean"), "cpulean/Main.lean")],
                      quick=[("gpu_runtime/", "remote", "/mnt/gloway/projects/v1-1-agentic-tool/gpu/gpu_runtime"),
                             ("driver/evidence_loop.py", "remote", "/mnt/gloway/projects/v1-1-agentic-tool/driver/evidence_loop.py")],
                      reads="README→driver→gpu_runtime/server.py→learner（按此序读代码）"),
                    C("c_agentic_sync", "运行快照工作区",
                      "reap-agentic-v1-1-sync：categorical-runtime 实验、服务启动脚本与哈希回执（未上云）。",
                      tags=["快照"],
                      paths=[("remote", "/mnt/gloway/projects/reap-agentic-v1-1-sync")]),
                    C("c_914_plan", "V1-1 计划总纲：9-14-plan（M0-M8）",
                      "接口矩阵、里程碑与门、模块分工；模块细节 modules/M1…M8。",
                      tags=["计划", "主线"],
                      paths=[("remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-plan")],
                      links=[("github", T(P914, "main", "9-14-plan"), "GitHub · 9-14-plan/"),
                             ("github", B(P914, "main", "9-14-plan/README.md"), "README")],
                      quick=[("00 数学理论", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-plan/00-math-theory.md"),
                             ("01 接口", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-plan/01-architecture-interfaces.md"),
                             ("02 里程碑", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-plan/02-milestones-gates.md"),
                             ("03 引用", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-plan/03-references.md")],
                      reads="README→00→01→02→03；模块速览 entries 1",
                      lead=""),
                    C("c_914_code", "V1-1 代码骨架：9-14-code（m1-m8）",
                      "shared 契约 + M1 Lean MCTS / M2 工具环 / M3 多专家 / M4 GPU 推理 / M5 LoRA / M6 QLoRA / M7 课程 / M8 评测。",
                      tags=["代码", "主线", "仅骨架"],
                      paths=[("remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-code")],
                      links=[("github", T(P914, "main", "9-14-code"), "GitHub · 9-14-code/"),
                             ("github", B(P914, "main", "9-14-code/README.md"), "README")],
                      quick=[("M1 Lean MCTS", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-code/m1-lean-mcts/MCTSDriver.lean"),
                             ("M2 工具环", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-code/m2-tool-runtime/opencode_bridge.py"),
                             ("M3 多专家", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-code/m3-multiagent/expert_router.py"),
                             ("M7 课程", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-code/m7-curriculum/curriculum.py")]),
                    C("c_914_data", "数据与语料工程：9-14-data",
                      "目标与指标、语料清单、采集管线、题目生成、证明树、验证质量、训练与存储、风险与许可。",
                      tags=["数据", "远程"],
                      paths=[("remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-data")],
                      links=[("github", T(P914, "main", "9-14-data"), "GitHub · 9-14-data/")],
                      quick=[("00 目标与指标", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-data/00-goals-and-metrics.md"),
                             ("04 证明树", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-data/04-proof-trees.md")]),
                    C("c_marl", "多智能体 RL（MARL，下一步主线）",
                      "联合策略 π_joint 单调改进、信用分配、经验继承、种群/AlphaEvolve 类比与版本管理。"
                      "形式化已完整，代码仅有 M3 路由/Jaccard 奖励骨架。",
                      tags=["主线（预备）", "参考"],
                      paths=[("remote", "/mnt/gloway/projects/multi-agent-rl-alpha-proof")],
                      links=[("github", T(MARL, "main"), "GitHub 仓库"),
                             ("github", B(MARL, "main", "1-glance.md"), "1-glance.md"),
                             ("github", B(P914, "main", "9-14-plan/modules/M3-multiagent-experts/README.md"), "9-14 M3 模块")],
                      reads="1-glance → 9-14 M3 → M4（实现落点）"),
                ],
            },
            {
                "id": "p6", "title": "Part 6 · V2（实验性，非主线）",
                "lead": "只有在 V1/V1-1 稳定后才建议进入；核心是「元动作 + Eff 通道 + 塔上升」与自指不变量。",
                "items": [
                    C("c_v2_spec", "V2 规格：Reap.Agent（元层）",
                      "元动作 + Eff 通道 + 塔上升（库增长）；四条红线：自指切开/证明≠计算/验证门/动作合法=类型检查。",
                      tags=["实验性"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/explain/reap-mcts-lean-v2"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/explain/reap-mcts-lean-v2")],
                      links=[("github", T(RNUM, "master", "explain/reap-mcts-lean-v2"), "GitHub · 规格目录")],
                      quick=[("00 总览", "wsl", "/home/zhai/project/reap/new-update-model/explain/reap-mcts-lean-v2/00-overview.md"),
                             ("01 Eff 通道", "wsl", "/home/zhai/project/reap/new-update-model/explain/reap-mcts-lean-v2/01-eff-channel.md"),
                             ("02 动作空间", "wsl", "/home/zhai/project/reap/new-update-model/explain/reap-mcts-lean-v2/02-action-space.md"),
                             ("04 训练与指标", "wsl", "/home/zhai/project/reap/new-update-model/explain/reap-mcts-lean-v2/04-training-and-metrics.md")],
                      reads="00→01→02→03→04"),
                    C("c_v2_code", "V2 code-1：最小可运行骨架（原型）",
                      "Lean Effect/MetaActions/Tower + Python harness（eff 白名单 / 塔 / runner）+ 真实验证入塔（22 塔）。",
                      tags=["实验性", "代码", "原型"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/reap-mcts-lean-v2-code-1"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/lean-v2")],
                      links=[("github", T(RNUM, "master", "reap-mcts-lean-v2-code-1"), "GitHub · code-1"),
                             ("github", B(RNUM, "master", "reap-mcts-lean-v2-code-1/README.md"), "README")],
                      quick=[("v2/eff_registry.py", "remote", "/mnt/gloway/projects/reap-new-update-model/reap-mcts-lean-v2-code-1/v2/eff_registry.py"),
                             ("v2/tower.py", "remote", "/mnt/gloway/projects/reap-new-update-model/reap-mcts-lean-v2-code-1/v2/tower.py"),
                             ("v2/mcts_loop.py", "remote", "/mnt/gloway/projects/reap-new-update-model/reap-mcts-lean-v2-code-1/v2/mcts_loop.py")]),
                    C("c_v2_public", "V2 / RSI 公开镜像",
                      "new-reap-mcts-ttt-public（MCTS+Lean+TTT 脱敏快照）、reap-rsi-public（RSI 公开版）。",
                      tags=["公开镜像"],
                      paths=[("remote", "/mnt/gloway/projects/reap-rsi-public")],
                      links=[("github", T(TTT, "main"), "new-reap-mcts-ttt-public"),
                             ("github", T(RSI, "master"), "reap-rsi-public")]),
                ],
            },
            {
                "id": "p7", "title": "Part 7 · Lean 环境",
                "lead": "主线 4.28；只有 v2/reap-agentic-v1-1 用 4.33.0-rc2。环境重建看 environment-spec，容器看 docker/。",
                "items": [
                    C("c_lean_f", "Lean 环境（主线 4.28）",
                      "new-v1-gather-source-code-cpu / v1-1-agentic-tool / mathlib4 = 4.28；reap-agentic-v1-1/cpulean = 4.33.0-rc2（例外）。",
                      tags=["环境"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/new-v1-gather-source-code-cpu"),
                             ("remote", "/mnt/gloway/projects/v1-1-agentic-tool/cpulean"),
                             ("remote", "/mnt/gloway/projects/lean-corpus/mathlib4"),
                             ("remote", "/mnt/gloway/projects/reap-agentic-v1-1/cpulean")],
                      links=[("github", B(RNUM, "master", "new-v1-gather-source-code-cpu/lean-toolchain"), "lean-toolchain"),
                             ("github", B(TOOL, "main", "cpulean/lean-toolchain"), "cpulean lean-toolchain"),
                             ("github", T(RNUM, "master", "docker"), "docker/"),
                             ("github", T(RNUM, "master", "environment-spec"), "environment-spec")]),
                    C("c_lean_wsl", "本机 Lean 环境（WSL）",
                      "elan 部署、toolchains（4.28.0-rc1 / 4.28.0 / 4.33.0-rc2）、reap lean-toolchain。",
                      tags=["环境"],
                      paths=[("wsl", "/home/zhai/project/Lean/deployed"),
                             ("wsl", "/home/zhai/.elan/toolchains"),
                             ("wsl", "/home/zhai/project/reap/lean-toolchain")]),
                    {"type": "table", "id": "t_gloway", "title": "F 盘：/mnt/gloway/projects（实验机主盘，私有版信息）",
                     "cols": ["目录", "内容", "GitHub"],
                     "rows": [
                         ["reap-new-update-model", "V1 主仓库：v1-spec / app / v1-result / nanoproof / v2", f"[RNUM]({T(RNUM,'master')})"],
                         ["reap-new-update-model-value-head", "价值头训练工作区（私有）", "（私有）"],
                         ["reap-publicize-work / reap-rsi-public", "公开化整理与脱敏公开版", f"[RSI]({T(RSI,'master')})"],
                         ["reap-agentic-v1-1 / v1-1-agentic-tool", "V1-1 CPU+GPU", f"[AG]({T(AG,'main')}) · [TOOL]({T(TOOL,'main')})"],
                         ["9-14-project-my-new-linux", "V1-1 计划与代码（M0-M8 + 数据）", f"[P914]({T(P914,'main')})"],
                         ["multi-agent-rl-alpha-proof", "多智能体扩展分析", f"[MARL]({T(MARL,'main')})"],
                         ["reap-gap-advance-alpha-proof", "REAP×AlphaProof 差距分析", f"[RGAP]({T(RGAP,'main')})"],
                         ["lean-corpus/mathlib4", "mathlib4（Lean v4.28.0）", "[leanprover-community/mathlib4](https://github.com/leanprover-community/mathlib4)"],
                     ]},
                    {"type": "table", "id": "t_lexar", "title": "E 盘：/mnt/lexar/projects（私有版信息）",
                     "cols": ["目录", "内容"],
                     "rows": [
                         ["reap/alpha-proof-original-math-version", "AlphaProof 档案的 E 盘镜像"],
                         ["lean", "Lean 工具链与实验（4.33.0-rc2、mathlib）"],
                         ["math-ai-base-data", "数学 AI 数据 / hot papers"],
                         ["Unimath / TALOS-V2 / alpha-system / alpha-zero-general", "形式化与 Alpha 系实验"],
                     ]},
                    {"type": "table", "id": "t_win", "title": "Windows 磁盘（私有版信息）",
                     "cols": ["挂载", "内容"],
                     "rows": [
                         ["/mnt/d", "Windows D 盘（下载、程序）"],
                         ["/mnt/e", "E 盘：当前为空（掉线）"],
                     ]},
                ],
            },
            {
                "id": "p8", "title": "Part 8 · GitHub / HuggingFace / 论文总表",
                "items": [
                    {"type": "table", "id": "t_gh", "title": "GitHub：项目仓库（17 公开 + 2 私有）",
                     "cols": ["仓库", "简介", "直链"],
                     "rows": [
                         ["alpha-proof-original-math-version", "AlphaProof 数学重构档案（21 篇）", f"[repo]({AP})"],
                         ["alphaproof-official-materials", "官方伪代码 + 补充材料", f"[repo]({APM})"],
                         ["gap-advance-plan-of-nano-proof-v1-m1", "nanoproof 差距/超越/路线", f"[repo]({GAP})"],
                         ["reap-source-code-explain", "REAP 源码精读 8 篇", f"[repo]({REAPS})"],
                         ["reap-gap-advance-alpha-proof", "REAP×AlphaProof 差距分析", f"[repo]({RGAP})"],
                         ["reap-new-update-model", "V1 主仓库（specs + app + v1-result + v2）", f"[repo]({RNUM})"],
                         ["reap-rsi-public", "RSI 脱敏公开版", f"[repo]({RSI})"],
                         ["new-reap-mcts-ttt-public", "MCTS+Lean+TTT 公开快照", f"[repo]({TTT})"],
                         ["reap-agentic-v1-1 / v1-1-agentic-tool", "V1-1 CPU+GPU", f"[AG]({AG}) · [TOOL]({TOOL})"],
                         ["9-14-project-my-new-linux", "V1-1 计划与代码（M0-M8）", f"[repo]({P914})"],
                         ["multi-agent-rl-alpha-proof", "多智能体扩展", f"[repo]({MARL})"],
                         ["ml-theory-reference", "ML 数学理论 13 主题", f"[repo]({MLT})"],
                         ["mcts-theory-learning", "MCTS+RL 数学笔记", f"[repo]({MCTS})"],
                         ["Lean-source-code-learning-to-know-reap", "Lean4 源码学习 13 篇", f"[repo]({LEAN})"],
                         ["jev-alpha-proof-analysis", "Jev × AlphaProof 校准分析（支线）", f"[repo]({JEV})"],
                         ["reap-roadmap", "本导航页（公开版）", f"[repo]({ROAD})"],
                         ["nanoproof-value-head", "nanoproof fork（value head 适配）", f"[repo]({NANOF})"],
                         ["reap-alpha-proof / reap-new-update-model-value-head", "私有工作区（登录后可开）", "—"],
                     ]},
                    {"type": "table", "id": "t_hf", "title": "HuggingFace：WufuJu",
                     "cols": ["模型", "说明", "直链"],
                     "rows": [
                         ["reap-value-head-v1-scaling", "价值头 v1（scaling 实验）", "[HF](https://huggingface.co/WufuJu/reap-value-head-v1-scaling)"],
                         ["alpha-proof-open-v1", "开放 v1 工件", "[HF](https://huggingface.co/WufuJu/alpha-proof-open-v1)"],
                         ["v1-1-fullv3-artifact", "V1-1 full-v3 工件", "[HF](https://huggingface.co/WufuJu/v1-1-fullv3-artifact)"],
                         ["internlm2-5-step-prover-critic", "step-prover-critic", "[HF](https://huggingface.co/WufuJu/internlm2-5-step-prover-critic)"],
                         ["FrenzyMath/REAL-Prover（基座）", "Qwen2.5-Math-7B 微调", "[HF](https://huggingface.co/FrenzyMath/REAL-Prover)"],
                     ]},
                    {"type": "table", "id": "t_refs", "title": "论文与官方资料",
                     "cols": ["资料", "地址"],
                     "rows": [
                         ["AlphaProof（Nature 2025）", "doi:10.1038/s41586-025-09833-y"],
                         ["AlphaProof Nexus（2026）", "arXiv:2605.22763"],
                         ["REAL-Prover", "arXiv:2505.20613"],
                     ]},
                ],
            },
        ],
    },
    {
        "id": "m2", "title": "模块二 · 预备知识与支线",
        "parts": [
            {
                "id": "q1", "title": "Part 1 · Lean 源码学习（读 Reap 前置）",
                "lead": "只用读 LL-00→02→03→04→06；没有 Lean 基础时它是 reap-source-code-explain 01 的展开版。",
                "items": [
                    C("c_lean_series", "Lean4 源码学习 13 篇（LL-00…12）",
                      "Expr 层级、kernel、metavar、monad、tactic 框架、LocalContext、声明与预处理、消息/位置、选项、库建议、widget/RPC。",
                      tags=["预备"],
                      paths=[("wsl", "/home/zhai/project/Lean-source-code-learning-to-know-reap")],
                      links=[("github", T(LEAN, "main"), "GitHub 仓库")],
                      quick=[("LL-00 计划", "wsl", "/home/zhai/project/Lean-source-code-learning-to-know-reap/LL-00-README-plan.md"),
                             ("LL-02 Expr", "wsl", "/home/zhai/project/Lean-source-code-learning-to-know-reap/LL-02-expr-levels.md"),
                             ("LL-03 Kernel", "wsl", "/home/zhai/project/Lean-source-code-learning-to-know-reap/LL-03-kernel-type-checker.md"),
                             ("LL-04 Metavar", "wsl", "/home/zhai/project/Lean-source-code-learning-to-know-reap/LL-04-metavars-defeq.md"),
                             ("LL-06 Tactic", "wsl", "/home/zhai/project/Lean-source-code-learning-to-know-reap/LL-06-tactic-framework.md")],
                      reads="LL-00→02→03→04→06→07；其余按需"),
                ],
            },
            {
                "id": "q2", "title": "Part 2 · MCTS + RL 数学笔记（读搜索与价值头前置）",
                "lead": "1→5→6→8→9 是与 AlphaProof/V1 直接相关的五篇；3/4 是集中不等式证明；10-15 是梯度/优化复习。",
                "items": [
                    C("c_mcts_series", "mcts-theory-learning（14 篇）",
                      "bandit→UCB1→UCT→PUCT→AlphaZero→AlphaProof→Q-transform 尺度→主 RL/TTRL/价值头；另含 Hoeffding/Markov 证明与优化基础。",
                      tags=["预备", "核心"],
                      paths=[("remote", "/home/a/文档/mcts-theory-learning")],
                      links=[("github", T(MCTS, "main"), "GitHub 仓库")],
                      quick=[("1 bandit→PUCT", "remote", "/home/a/文档/mcts-theory-learning/1-.md"),
                             ("5 MCTS+RL", "remote", "/home/a/文档/mcts-theory-learning/5-mcts-rl.md"),
                             ("6 AlphaProof", "remote", "/home/a/文档/mcts-theory-learning/6-alpha-proof-mcts-rl.md"),
                             ("8 Q-transform 尺度", "remote", "/home/a/文档/mcts-theory-learning/8-6-q-transform-reason-1.md"),
                             ("9 主RL/TTRL+价值头", "remote", "/home/a/文档/mcts-theory-learning/9-mainrl-ttrl-llm-value-head.md")],
                      reads="1→3→4-3→5→6→7-6→8-6→9"),
                ],
            },
            {
                "id": "q3", "title": "Part 3 · 主题参考资料（13 个主题，云端镜像）",
                "lead": "每个主题先读 00 导读；「服务对象」列指出它支撑哪个开发模块。全部 13 个主题已镜像到 ml-theory-reference。",
                "items": [
                    {"type": "table", "id": "t_topics", "title": "13 个主题（每个先读 00-导读与目录）",
                     "cols": ["主题", "首读", "服务对象"],
                     "rows": [
                         ["Transformer数学理论参考资料", f"[00]({B(MLT,'main','topics/Transformer数学理论参考资料/00-导读与目录.md')})", "档案 10-11；V1 policy 端点"],
                         ["ttt-参考资料", f"[00]({B(MLT,'main','topics/ttt-参考资料/00-导读与目录.md')})", "TTT/RTTT（V1 主线、V2）"],
                         ["样本效率理论参考资料", f"[00]({B(MLT,'main','topics/样本效率理论参考资料/00-导读与目录.md')})", "价值头 / 课程 / 样本预算"],
                         ["信息几何理论参考资料", f"[00]({B(MLT,'main','topics/信息几何理论参考资料/00-导读与目录.md')})", "TTT 与 RL 理论背景"],
                         ["RLVR-OPSD-参考资料", f"[00]({B(MLT,'main','topics/RLVR-OPSD-参考资料/00-总览与阅读路线.md')})", "GRPO/TTTRL（M4）"],
                         ["残差连接理论参考资料", f"[00]({B(MLT,'main','topics/残差连接理论参考资料/00-导读与目录.md')})", "网络结构与优化背景"],
                         ["贝叶斯概率与机器学习参考资料", f"[00]({B(MLT,'main','topics/贝叶斯概率与机器学习参考资料/00-导读与目录.md')})", "工具环证据（V1-1）/ 价值"],
                         ["随机微分方程与机器学习参考资料", f"[00]({B(MLT,'main','topics/随机微分方程与机器学习参考资料/00-导读与目录.md')})", "生成 / 连续时间背景"],
                         ["高维概率论参考资料", f"[00]({B(MLT,'main','topics/高维概率论参考资料/00-导读与目录.md')})", "集中不等式 / MCTS 理论"],
                         ["扩散模型数学理论参考资料", f"[00]({B(MLT,'main','topics/扩散模型数学理论参考资料/00-导读与目录.md')})", "背景（选读）"],
                         ["LoRA微调数学理论参考资料", f"[00]({B(MLT,'main','topics/LoRA微调数学理论参考资料/00-导读与目录.md')})", "V1/V1-1 GPU 训练"],
                         ["RNN-LSTM数学理论参考资料", f"[00]({B(MLT,'main','topics/RNN-LSTM数学理论参考资料/00-导读与目录.md')})", "序列建模背景（选读）"],
                         ["元学习参考资料", f"[00]({B(MLT,'main','topics/元学习参考资料/00-导读与目录.md')})", "TTT / 自改进"],
                     ]},
                ],
            },
            {
                "id": "q4", "title": "Part 4 · Jev × AlphaProof（支线参考，仅供校准思路）",
                "lead": "不是主线：只在做价值头校准评测、预算分配或 TTT 训练回路时查。两篇最有用：分析 03（评分规则/删失）与 04（自采样定理）。",
                "items": [
                    C("c_jev_ap", "Jev × AlphaProof 分析（00-08）★",
                      "校准打分头 vs 价值头：协议绑定、proper 损失、删失纠正、并行打分、预算/教师路由、实验协议。",
                      tags=["支线", "参考"],
                      paths=[("remote", "/home/a/文档/jev-and-open-rebuilt/alpha-proof")],
                      links=[("github", T(JEV, "main", "alpha-proof"), "GitHub · alpha-proof/")],
                      quick=[("00 总览", "remote", "/home/a/文档/jev-and-open-rebuilt/alpha-proof/00-总览与导读.md"),
                             ("02 对象辨析", "remote", "/home/a/文档/jev-and-open-rebuilt/alpha-proof/02-对象辨析-价值头与校准打分头.md"),
                             ("03 评分规则/删失", "remote", "/home/a/文档/jev-and-open-rebuilt/alpha-proof/03-Proper评分规则与价值目标的统一语言.md"),
                             ("04 自采样定理", "remote", "/home/a/文档/jev-and-open-rebuilt/alpha-proof/04-RLCD自采样定理与引导目标.md"),
                             ("07 设计与实验", "remote", "/home/a/文档/jev-and-open-rebuilt/alpha-proof/07-可迁移设计清单与实验协议.md")],
                      reads="00→02→03→04→05；只读两章：03 与 04"),
                    C("c_jev", "Jev 全景笔记（00-13）",
                      "TypeSafe System One/Jev：校准决策、RLCD、API 原语、开源复刻三路线、数学推导与开放问题。",
                      tags=["支线", "参考"],
                      paths=[("remote", "/home/a/文档/jev-and-open-rebuilt")],
                      links=[("github", T(JEV, "main", "jev"), "GitHub · jev/")],
                      quick=[("00 总览", "remote", "/home/a/文档/jev-and-open-rebuilt/00-总览与导读.md"),
                             ("03 架构/API", "remote", "/home/a/文档/jev-and-open-rebuilt/03-Jev架构与API机制.md"),
                             ("08 校准数学", "remote", "/home/a/文档/jev-and-open-rebuilt/08-数学I-概率校准与Proper Scoring Rules.md"),
                             ("09 RLCD 推导", "remote", "/home/a/文档/jev-and-open-rebuilt/09-数学II-强化学习与RLCD推导.md")],
                      reads="00→01→03→12（工程）；08→09→10→11（数学）"),
                ],
            },
        ],
    },
]
