# -*- coding: utf-8 -*-
"""REAP / AlphaProof 研究导航 —— 数据模型（可手工维护）。

路径机器代号:
  wsl    = 笔记本 WSL (zhai@LAPTOP-IR9BS02N, distro Ubuntu-D)
  remote = my-new-linux (a@my-new-linux, F盘=/mnt/gloway, E盘=/mnt/lexar)
"""


def C(cid, title, desc, tags=(), paths=(), links=(), quick=(), reads=""):
    return {"id": cid, "title": title, "desc": desc, "tags": list(tags),
            "paths": [tuple(p) for p in paths],
            "links": [tuple(l) for l in links],
            "quick": [tuple(q) for q in quick], "reads": reads}


META = {
    "title": "REAP / AlphaProof 研究导航",
    "subtitle": "两大模块 · 全部仓库/文件夹/文档/模型 的索引与阅读顺序",
    "generated": "2026-09-18",
    "wsl_distro": "Ubuntu-D",
}

NOTES = [
    ("价值头语义（重要更正）",
     "权威定义见 AlphaProof 分析档案 00-overview：d(s) = -V(s) ≥ 0 是「期望剩余步数」（长分支取 max），"
     "不是百分比。旧 V1 spec/历史文档中「价值头输出百分比」的说法与原文不符，以档案 00/02 与 "
     "new-update-model/app/VALUE_HEAD.md（score=-V(s)，V∈[-1,1]）为准。"),
    ("E 盘现状",
     "本机 WSL 的 /mnt/e 当前为空（E 盘掉线/未挂载），alpha-proof-original-math-version 的本地符号链接已断。"
     "请用 .wsl-backup 目录或 F 盘镜像 /mnt/gloway/projects/reap-new-update-model 下的同名内容。"),
    ("Lean 版本",
     "主线 = Lean 4.28：reap=v4.28.0-rc1、new-v1-gather-source-code-cpu=v4.28.0-rc1、"
     "v1-1-agentic-tool/cpulean=v4.28.0、F 盘 lean-corpus/mathlib4=v4.28.0。"
     "例外：V2 的 reap-agentic-v1-1/cpulean 用 v4.33.0-rc2；formal-imo / miniF2F / Nexus 用 v4.27.0。"),
    ("私有仓库",
     "reap-alpha-proof 与 reap-new-update-model-value-head 为私有仓库（登录后可开）；"
     "其余 10 个仓库均公开。"),
    ("Windows/Edge 打不开 wsl.localhost？",
     "你的 C:\\Users\\zhai\\.wslconfig 使用 networkingMode=mirrored，此模式下 \\\\wsl.localhost 不可用（WSL 已知限制）。"
     "在 Edge 里请选「Windows · VSCode 跳转」模式：路径点击会交给 VS Code 打开（WSL 用 remote-wsl，F/E 盘用 Remote-SSH）。"),
]

# 快速阅读顺序（顶部表格）
QUICK = [
    ("1. 读原理（AlphaProof 怎么 working）",
     "分析档案 00→01→03→02→04→06→05→07→08；深挖看 10/13/14；重建路线 09→19→20",
     ["c_dossier"]),
    ("2. 读源码（Reap 怎么实现）",
     "reap-source-code-explain 01→02→03→04→05→06→07→08（没 Lean 基础先看 01）",
     ["c_reap_source"]),
    ("3. 看差距与路线（nano/REAP vs AlphaProof）",
     "nano 分析 00→02→03→05→09；REAP 补充 00-index→04→06",
     ["c_nano_analysis", "c_reap_gap"]),
    ("4. 跑/改 V1（主线）",
     "v1-spec 00→01→02→04→05→07；training-methods 00→06；实验档案 v1-result 复现",
     ["c_v1_spec", "c_v1_result"]),
    ("5. 改价值头",
     "档案 02+12 → app/VALUE_HEAD.md → HF reap-value-head-v1-scaling → MCTS 笔记 9",
     ["c_v1_value_head"]),
    ("6. V1-1 agentic-tool（主线）",
     "9-14-plan 00→01→02→03 → reap-agentic-v1-1 README → v1-1-agentic-tool",
     ["c_914_plan", "c_agentic_repo"]),
    ("7. V2（实验性，非主线）",
     "explain 7→8 → v2 spec 00→04 → v2 code README",
     ["c_v2_spec", "c_v2_code"]),
]

MODULES = [
    {
        "id": "m1", "title": "模块一 · 项目",
        "parts": [
            {
                "id": "p1", "title": "Part 1 · AlphaProof 源头与官方资料（优先）",
                "items": [
                    C("c_nature", "原论文：AlphaProof (Nature 2025)",
                      "Hubert et al., Olympiad-level formal mathematical reasoning with RL。",
                      tags=["源头", "官方"],
                      paths=[("wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/refs-alpha-proof-paper-nature-2025.md"),
                             ("wsl", "/home/zhai/project/alphaproof-official-materials")],
                      links=[("doi", "https://doi.org/10.1038/s41586-025-09833-y", "doi 10.1038/s41586-025-09833-y"),
                             ("web", "https://www.nature.com/articles/s41586-025-09833-y", "Nature 页面")]),
                    C("c_official", "官方伪代码与补充材料",
                      "pseudocode.py（RL/autoformalize/variant generation）+ supplementary pdf/txt；"
                      "无独立官方仓库，来源=Nature 补充材料。",
                      tags=["官方"],
                      paths=[("wsl", "/home/zhai/project/alphaproof-official-materials")]),
                    C("c_dossier", "分析档案：alpha-proof-original-math-version ★",
                      "21 篇数学化重构：公式级讲解 + 重建路线 + 实验协议；V1/V1-1 的语义基准。",
                      tags=["核心", "优先"],
                      paths=[("wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup")],
                      links=[("github", "https://github.com/wufuju2023-cell/alpha-proof-original-math-version", "GitHub")],
                      quick=[("00 总览", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/00-overview.md"),
                             ("01 Lean 环境", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/01-lean-env.md"),
                             ("03 搜索", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/03-search.md"),
                             ("09 重建计划", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/09-reconstruction-plan.md"),
                             ("20 实验套件", "wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/20-experiment-suite.md")],
                      reads="学习 00→01→03→02→04→06→05→07→08；重建 09→19→20；对照 08+20"),
                    C("c_dossier_explain", "档案对照讲义：MCTS/PUCT",
                      "对档案公式的补充推导（1-13-mcts-puct）。",
                      tags=["参考"],
                      paths=[("wsl", "/home/zhai/project/reap/alpha-proof-original-math-version.wsl-backup/explain/1-13-mcts-puct.md")]),
                    C("c_nexus", "AlphaProof Nexus（2026 · Agent 论文）",
                      "arXiv:2605.22763「Advancing Mathematics Research with AI-Driven Formal Proof Search」；"
                      "Gemini+Lean 证明 9 个 Erdős 问题、44 个 OEIS 猜想。",
                      tags=["2026", "Agent"],
                      paths=[("wsl", "/home/zhai/project/alphaproof-nexus-results")],
                      links=[("arxiv", "https://arxiv.org/abs/2605.22763", "arXiv:2605.22763"),
                             ("github", "https://github.com/google-deepmind/alphaproof-nexus-results", "官方 repo")]),
                    C("c_hsy", "hsy AlphaProof 分析（0916，交叉核查）",
                      "11 篇：原版机制/TTRL/公开模型/nano 源码核查/Nexus/Matchmaker（Part 3 第 5 项）。",
                      tags=["参考", "远程"],
                      paths=[("remote", "/home/a/文档/hsy-alphaproof-public/0916")]),
                ],
            },
            {
                "id": "p2", "title": "Part 2 · NanoProof（开源 AlphaProof 复现）",
                "items": [
                    C("c_nano_upstream", "原始仓库：kripner/nanoproof",
                      "端到端开源 AlphaProof 风格 prover：~1.03B，MiniF2F-valid 52.7%@512。",
                      tags=["上游"],
                      links=[("github", "https://github.com/kripner/nanoproof", "kripner/nanoproof")]),
                    C("c_nano_fork", "你的 fork：nanoproof-value-head",
                      "value-head-adapter 分支；内含官方 pseudocode.py 副本与 PORTING_REAP_VALUE_HEAD.md。",
                      tags=["fork", "远程"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/nanoproof")],
                      links=[("github", "https://github.com/wufuju2023-cell/nanoproof-value-head", "GitHub fork")]),
                    C("c_nano_analysis", "分析仓库：gap-advance-plan-of-nano-proof-v1-m1 ★",
                      "差距 G1-G20、超越 A1-A11、路线 P0-P4、实验 E1-E20、代码地图与分数板。",
                      tags=["核心"],
                      paths=[("wsl", "/home/zhai/project/gap-advance-plan-of-nano-proof-v1-m1")],
                      links=[("github", "https://github.com/wufuju2023-cell/gap-advance-plan-of-nano-proof-v1-m1", "GitHub")],
                      quick=[("00 总览", "wsl", "/home/zhai/project/gap-advance-plan-of-nano-proof-v1-m1/00-overview.md"),
                             ("03 差距", "wsl", "/home/zhai/project/gap-advance-plan-of-nano-proof-v1-m1/03-gaps.md"),
                             ("05 未来计划", "wsl", "/home/zhai/project/gap-advance-plan-of-nano-proof-v1-m1/05-future-plan.md"),
                             ("09 代码地图", "wsl", "/home/zhai/project/gap-advance-plan-of-nano-proof-v1-m1/09-code-map.md")],
                      reads="00→01→02→03→04→05；动手前 09，复查数字 10"),
                    C("c_reap_gap", "REAP × AlphaProof 差距分析（F 盘补充）",
                      "00-index→04 reap-vs-alphaproof→06 roadmap；REAP 公式/验证/差距的补充材料。",
                      tags=["参考", "远程"],
                      paths=[("remote", "/mnt/gloway/projects/reap-gap-advance-alpha-proof")]),
                ],
            },
            {
                "id": "p3", "title": "Part 3 · REAP（上游框架）",
                "items": [
                    C("c_reap_upstream", "原始仓库：frenzymath/reap（+ IQuestLab 旧址）",
                      "Lean 内神经证明搜索：policy/value/premise 三端点 + MCTS（reap!! / reapMCTS）。",
                      tags=["上游"],
                      links=[("github", "https://github.com/frenzymath/reap", "frenzymath/reap"),
                             ("github", "https://github.com/IQuestLab/reap", "IQuestLab/reap")]),
                    C("c_reap_local", "你的 reap 工作区（私有 fork）",
                      "Reap/ 源码 + V1/V2 改动；reap-old 容器镜像来源。",
                      tags=["工作区", "私有"],
                      paths=[("wsl", "/home/zhai/project/reap")],
                      links=[("github", "https://github.com/wufuju2023-cell/reap-alpha-proof", "GitHub（私有）")]),
                    C("c_reap_source", "源码精读：reap-source-code-explain ★",
                      "8 篇：Lean4 入门→架构→树库→Step 验证→Generator→MCTS 内核→widget→测试。",
                      tags=["核心"],
                      paths=[("wsl", "/home/zhai/project/reap/reap-source-code-explain")],
                      quick=[("00 INDEX", "wsl", "/home/zhai/project/reap/reap-source-code-explain/00-INDEX.md"),
                             ("02 架构", "wsl", "/home/zhai/project/reap/reap-source-code-explain/02-architecture-overview.md"),
                             ("06 MCTS 内核", "wsl", "/home/zhai/project/reap/reap-source-code-explain/06-mcts-core.md"),
                             ("05 策略/价值/前提", "wsl", "/home/zhai/project/reap/reap-source-code-explain/05-policy-value-premise.md")],
                      reads="01→02→03→04→05→06→07→08（无 Lean 基础必须先 01）"),
                    C("c_real_prover", "REAL-Prover（7B 基座）",
                      "arXiv:2505.20613；Qwen2.5-Math-7B 微调，8B 级，Lean step prover。",
                      tags=["论文", "模型"],
                      links=[("arxiv", "https://arxiv.org/abs/2505.20613", "arXiv:2505.20613"),
                             ("github", "https://github.com/frenzymath/REAL-Prover", "GitHub"),
                             ("hf", "https://huggingface.co/FrenzyMath/REAL-Prover", "HF 权重")]),
                ],
            },
            {
                "id": "p4", "title": "Part 4 · V1（主线：REAL-Prover 7B + 价值头 + on-demand RTTT）",
                "items": [
                    C("c_v1_spec", "V1 规格：new-update-model/v1-spec ★",
                      "0 长训 + 用即学（on-demand RTTT）；含 policy/value/MCTS/课程/训练/评测/runbook。",
                      tags=["主线", "核心"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/v1-spec"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/v1-spec")],
                      quick=[("00 系统综述", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/00-overview.md"),
                             ("01 Policy&Value", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/01-policy-value.md"),
                             ("02 MCTS&验证器", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/02-mcts-verifier.md"),
                             ("04 训练", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/04-training.md"),
                             ("07 Runbook", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/07-runbook.md")],
                      reads="00→01→02→03→04→05→07（跑起来看 07）"),
                    C("c_v1_plan", "V1 研究计划：plan/（00-12）",
                      "动机、架构、MCTS 环境、数据、RL 参数更新、评测、路线图；TTT/RSI/课程/双模型。",
                      tags=["设计"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/plan"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/plan")],
                      quick=[("00 索引", "wsl", "/home/zhai/project/reap/new-update-model/plan/00-index.md"),
                             ("05 RL 更新", "wsl", "/home/zhai/project/reap/new-update-model/plan/05-rl-param-update.md"),
                             ("09 TTT", "wsl", "/home/zhai/project/reap/new-update-model/plan/09-test-time-training.md"),
                             ("12 双模型", "wsl", "/home/zhai/project/reap/new-update-model/plan/12-two-model-architecture.md")],
                      reads="00→01→02→03→05→08→09→12"),
                    C("c_v1_explain", "深度分析：explain/（1-13）",
                      "价值头作用、难题进步、harness、AlphaProof×Agent、元编程、V1/V2、上下文管理……",
                      tags=["分析"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/explain"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/explain")],
                      quick=[("1 价值头的作用", "wsl", "/home/zhai/project/reap/new-update-model/explain/1-价值头的作用.md"),
                             ("7 Reap V1/V2", "wsl", "/home/zhai/project/reap/new-update-model/explain/7-reap-v1-v2.md"),
                             ("10 MCTS 用途", "wsl", "/home/zhai/project/reap/new-update-model/explain/10-mcts-usage-and-alternatives.md"),
                             ("11 self-play vs TTT", "wsl", "/home/zhai/project/reap/new-update-model/explain/11-selfplay-alpha-zero-vs-reap-ttt.md")]),
                    C("c_v1_cpu_code", "V1 CPU 端代码（全量归集）",
                      "reap-upstream（原样）+ reap-training（Verdict/RolloutSink）+ python-driver（编排）。",
                      tags=["代码", "远程"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/new-v1-gather-source-code-cpu")],
                      quick=[("README", "remote", "/mnt/gloway/projects/reap-new-update-model/new-v1-gather-source-code-cpu/README.md")]),
                    C("c_v1_gpu_code", "V1 GPU 端代码（app/）",
                      "policy_server（RTTT）/ value_head / rttt_demo / train_value_head / v1_run / v1_sink。",
                      tags=["代码", "远程"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/app"),
                             ("wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-example/scripts")],
                      quick=[("VALUE_HEAD 说明", "remote", "/mnt/gloway/projects/reap-new-update-model/app/VALUE_HEAD.md")]),
                    C("c_v1_methods", "训练方法规格：v1-1-training-methods",
                      "数据/SFT/GRPO/TTTRL/值头/组合调度（阶段 A→C 全配置）。",
                      tags=["规格"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-methods"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/v1-spec/v1-1-training-methods")],
                      quick=[("00 索引", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-methods/00-index.md"),
                             ("03 RL(GRPO)", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-methods/03-rl-spec.md"),
                             ("04 TTTRL", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-methods/04-tttrl-spec.md")]),
                    C("c_v1_amd", "AMD 云规格与运行环境",
                      "v1-1-training-on-amd-cloud（W7900×4 / ROCm）+ environment-spec（环境复用规范）。",
                      tags=["基础设施"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-on-amd-cloud"),
                             ("wsl", "/home/zhai/project/environment-spec"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/environment-spec")],
                      quick=[("00 总览", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-on-amd-cloud/00-overview.md")]),
                    C("c_v1_example", "V1 环境/控制面示例：v1-1-training-example",
                      "instance 192G、SSH/opencli 自动化、env-sync、脚本与评测集（runs/eval_sets）。",
                      tags=["基础设施"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-example"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/v1-spec/v1-1-training-example")],
                      quick=[("README", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-example/README.md"),
                             ("control 00", "wsl", "/home/zhai/project/reap/new-update-model/v1-spec/v1-1-training-example/control/00-index.md")]),
                    C("c_v1_result", "V1 实验记录：v1-result ★",
                      "2026-08-28 Pell 实验：题内 TTT、跨题经验、并发调度；含证据 JSON、复现文档、CPU/GPU runtime。",
                      tags=["实验", "核心", "远程"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/v1-result")],
                      quick=[("README", "remote", "/mnt/gloway/projects/reap-new-update-model/v1-result/README.md"),
                             ("current/00 地图", "remote", "/mnt/gloway/projects/reap-new-update-model/v1-result/docs/current/00-总设计与阅读地图.md"),
                             ("current/01 题内 TTT", "remote", "/mnt/gloway/projects/reap-new-update-model/v1-result/docs/current/01-题内在线TTT.md"),
                             ("current/04 结果", "remote", "/mnt/gloway/projects/reap-new-update-model/v1-result/docs/current/04-实际实例与验收结果.md")],
                      reads="README→docs/current/00→01→04；复现 02-运行流程与复现"),
                    C("c_v1_value_head", "价值头：实现 + 工作区 + HF 权重 ★",
                      "共享 REAL-Prover backbone 的标量头（H→256→1, tanh, V∈[-1,1]）；scalar/distance 两种输出模式。",
                      tags=["模型", "核心"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model-value-head"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/app/VALUE_HEAD.md"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/discussion/alphaproof-value-head")],
                      links=[("hf", "https://huggingface.co/WufuJu/reap-value-head-v1-scaling", "HF: reap-value-head-v1-scaling")],
                      reads="NEW: 档案 02+12 先定语义；再 app/VALUE_HEAD.md；HF 只是权重"),
                    C("c_v1_models", "模型集散：HF 主页 WufuJu",
                      "价值头 v1-scaling、alpha-proof-open-v1、v1-1-fullv3-artifact、internlm2.5 step-prover-critic。",
                      tags=["模型"],
                      links=[("hf", "https://huggingface.co/WufuJu", "HF 主页"),
                             ("hf", "https://huggingface.co/FrenzyMath/REAL-Prover", "基座 REAL-Prover")]),
                    C("c_v1_bench", "评测基准仓库（本机）",
                      "formal-imo（258 题）与 miniF2F 的 Lean 形式化（Lean 4.27）。",
                      tags=["评测"],
                      paths=[("wsl", "/home/zhai/project/formal-imo"), ("wsl", "/home/zhai/project/miniF2F")]),
                ],
            },
            {
                "id": "p5", "title": "Part 5 · V1-1 agentic-tool（主线：CPU Lean + GPU 工具环）",
                "items": [
                    C("c_agentic_repo", "仓库：reap-agentic-v1-1 ★",
                      "Lean CPU（本地 mathlib）+ GPU Python 传输桥；agent 工具环作为 Bayes 先验/后验证据。",
                      tags=["主线", "代码"],
                      paths=[("remote", "/mnt/gloway/projects/reap-agentic-v1-1")],
                      links=[("github", "https://github.com/wufuju2023-cell/reap-agentic-v1-1", "GitHub")],
                      quick=[("README", "remote", "/mnt/gloway/projects/reap-agentic-v1-1/README.md"),
                             ("cpulean", "remote", "/mnt/gloway/projects/reap-agentic-v1-1/cpulean"),
                             ("driver", "remote", "/mnt/gloway/projects/reap-agentic-v1-1/driver")]),
                    C("c_agentic_tool", "仓库：v1-1-agentic-tool ★",
                      "兼容容器 Lean-4.28/Mathlib 的 CPU runtime（Main.lean）+ gpu_runtime（33 模块）+ 证据循环。",
                      tags=["主线", "代码"],
                      paths=[("remote", "/mnt/gloway/projects/v1-1-agentic-tool")],
                      links=[("github", "https://github.com/wufuju2023-cell/v1-1-agentic-tool", "GitHub")],
                      quick=[("README", "remote", "/mnt/gloway/projects/v1-1-agentic-tool/README.md"),
                             ("driver/evidence_loop", "remote", "/mnt/gloway/projects/v1-1-agentic-tool/driver/evidence_loop.py")]),
                    C("c_agentic_sync", "同步工作区（运行快照）",
                      "reap-agentic-v1-1-sync：categorical-runtime 系列实验、服务启动脚本与哈希回执。",
                      tags=["远程"],
                      paths=[("remote", "/mnt/gloway/projects/reap-agentic-v1-1-sync")]),
                    C("c_914_plan", "V1-1 计划总纲：9-14-plan（M0-M8）",
                      "多智能体 AlphaProof 工程：接口矩阵、里程碑、模块分工（LoRA/QLoRA 双轨）。",
                      tags=["计划", "主线"],
                      paths=[("remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-plan")],
                      links=[("github", "https://github.com/wufuju2023-cell/9-14-project-my-new-linux", "GitHub")],
                      quick=[("README", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-plan/README.md"),
                             ("00 数学理论", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-plan/00-math-theory.md"),
                             ("01 接口", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-plan/01-architecture-interfaces.md"),
                             ("03 引用", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-plan/03-references.md")],
                      reads="README→00→01→02→03；模块细节 modules/M1..M8"),
                    C("c_914_code", "V1-1 代码骨架：9-14-code（m1-m8）",
                      "shared 契约 + Lean MCTS/工具环/多专家/GPU 推理/LoRA/QLoRA/课程/评测。",
                      tags=["代码", "主线"],
                      paths=[("remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-code")],
                      quick=[("README", "remote", "/mnt/gloway/projects/9-14-project-my-new-linux/9-14-code/README.md")]),
                    C("c_marl_glance", "多智能体形式化分析：1-glance.md",
                      "联合策略 π_joint 单调改进、经验继承、MARL/AlphaEvolve 结合（V1-1/V2 背景）。",
                      tags=["分析", "远程"],
                      paths=[("remote", "/mnt/gloway/projects/multi-agent-rl-alpha-proof")]),
                ],
            },
            {
                "id": "p6", "title": "Part 6 · V2（实验性，非主线）",
                "items": [
                    C("c_v2_spec", "V2 规格：Reap.Agent（元层）",
                      "元动作 + Eff 通道 + 塔上升（库增长）；四条红线：自指切开/证明≠计算/验证门/动作合法=类型检查。",
                      tags=["实验性"],
                      paths=[("wsl", "/home/zhai/project/reap/new-update-model/explain/reap-mcts-lean-v2"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/explain/reap-mcts-lean-v2")],
                      quick=[("00 总览", "wsl", "/home/zhai/project/reap/new-update-model/explain/reap-mcts-lean-v2/00-overview.md"),
                             ("01 Eff 通道", "wsl", "/home/zhai/project/reap/new-update-model/explain/reap-mcts-lean-v2/01-eff-channel.md"),
                             ("02 动作空间", "wsl", "/home/zhai/project/reap/new-update-model/explain/reap-mcts-lean-v2/02-action-space.md")]),
                    C("c_v2_code", "V2 code-1：最小可运行骨架",
                      "Lean Effect/MetaActions/Tower + Python harness（eff 白名单/塔/runner）+ 真实验证入塔（22 塔）。",
                      tags=["实验性", "代码"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/reap-mcts-lean-v2-code-1"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/lean-v2"),
                             ("remote", "/mnt/gloway/projects/reap-new-update-model/new-v2-gather-source-code")],
                      quick=[("README", "remote", "/mnt/gloway/projects/reap-new-update-model/reap-mcts-lean-v2-code-1/README.md")]),
                    C("c_v2_public", "V2/RSI 公开镜像",
                      "new-reap-mcts-ttt-public（脱敏快照）、reap-rsi-public（RSI: search×RL×TTT）。",
                      tags=["公开镜像"],
                      paths=[("remote", "/mnt/gloway/projects/reap-rsi-public"),
                             ("remote", "/mnt/gloway/projects/reap-publicize-work")],
                      links=[("github", "https://github.com/wufuju2023-cell/new-reap-mcts-ttt-public", "new-reap-mcts-ttt-public"),
                             ("github", "https://github.com/wufuju2023-cell/reap-rsi-public", "reap-rsi-public")]),
                ],
            },
            {
                "id": "p7", "title": "Part 7 · Lean 环境与磁盘（F盘 / E盘 / 本机）",
                "items": [
                    C("c_lean_wsl", "本机 Lean 环境（WSL 笔记本）",
                      "elan 部署于 /home/zhai/project/Lean/deployed；toolchains：4.28.0-rc1、4.28.0、4.33.0-rc2。",
                      tags=["环境"],
                      paths=[("wsl", "/home/zhai/project/Lean/deployed"),
                             ("wsl", "/home/zhai/.elan/toolchains"),
                             ("wsl", "/home/zhai/project/reap/lean-toolchain")],
                      reads="reap=4.28.0-rc1；formal-imo/miniF2F/Nexus=4.27.0"),
                    C("c_lean_f", "F 盘 Lean 环境（my-new-linux）",
                      "主线 4.28：new-v1-gather-source-code-cpu / v1-1-agentic-tool / lean-corpus/mathlib4；"
                      "例外：reap-agentic-v1-1/cpulean=4.33.0-rc2。",
                      tags=["环境", "远程"],
                      paths=[("remote", "/mnt/gloway/projects/reap-new-update-model/new-v1-gather-source-code-cpu"),
                             ("remote", "/mnt/gloway/projects/v1-1-agentic-tool/cpulean"),
                             ("remote", "/mnt/gloway/projects/lean-corpus/mathlib4"),
                             ("remote", "/mnt/gloway/projects/reap-agentic-v1-1/cpulean")],
                      reads="E 盘 lexar/projects/lean 还有一套 4.33.0-rc2 工具链与 mathlib 实验"),
                    {"type": "table", "id": "t_gloway", "title": "F 盘：/mnt/gloway/projects（my-new-linux，2TB，主盘）",
                     "cols": ["目录", "内容", "GitHub"],
                     "rows": [
                         ["reap-new-update-model", "V1 主仓库：v1-spec / app / v1-result / nanoproof / v2 等", "wufuju2023-cell/reap-new-update-model（master）"],
                         ["reap-new-update-model-value-head", "价值头训练工作区（私有）", "（私有）"],
                         ["reap-new-update-model-master", "主线快照副本（含 github 归档）", "—"],
                         ["reap-publicize-work", "公有化整理分支（PUBLICATION.md）", "→ reap-rsi-public"],
                         ["reap-rsi-public", "RSI 脱敏公开版（search×RL×TTT）", "wufuju2023-cell/reap-rsi-public"],
                         ["reap-agentic-v1-1", "V1-1 Lean CPU + GPU 桥", "wufuju2023-cell/reap-agentic-v1-1"],
                         ["v1-1-agentic-tool", "V1-1 独立 CPU runtime + gpu_runtime", "wufuju2023-cell/v1-1-agentic-tool"],
                         ["reap-agentic-v1-1-sync", "同步工作区/运行快照", "—"],
                         ["9-14-project-my-new-linux", "多智能体 AlphaProof：9-14-plan + 9-14-code（M1-M8）", "wufuju2023-cell/9-14-project-my-new-linux"],
                         ["reap-gap-advance-alpha-proof", "REAP×AlphaProof 差距分析（00-06）", "—"],
                         ["multi-agent-rl-alpha-proof", "多智能体 RL 形式化（1-glance.md）", "—"],
                         ["lean-corpus/mathlib4", "mathlib4（Lean v4.28.0）", "leanprover-community/mathlib4"],
                         ["opencli-fork", "浏览器自动化 fork（工具链依赖）", "—"],
                     ]},
                    {"type": "table", "id": "t_lexar", "title": "E 盘：/mnt/lexar/projects（my-new-linux，512G，辅助）",
                     "cols": ["目录", "内容"],
                     "rows": [
                         ["reap/alpha-proof-original-math-version", "AlphaProof 档案的 E 盘镜像"],
                         ["lean", "Lean 工具链与实验（4.33.0-rc2、mathlib、SNL-Basics 等）"],
                         ["math-ai-base-data", "数学 AI 数据/hot papers（MinerU 流水线）"],
                         ["Unimath / TALOS-V2 / alpha-system / alpha-zero-general", "形式化/Alpha 系实验"],
                         ["computer-science-learning / category-expert-lab / k-theory-experiment", "学习与专家实验"],
                         ["math-expert-system-cumulative", "数学专家系统累积资料"],
                         ["pi-agent / opencode / kilocode / hermes-*", "Agent 工具与运行时"],
                     ]},
                    {"type": "table", "id": "t_win", "title": "本机 Windows 磁盘（WSL /mnt/*）",
                     "cols": ["挂载", "内容"],
                     "rows": [
                         ["/mnt/d", "Windows D 盘：下载、程序（非项目主区）"],
                         ["/mnt/e", "E 盘：当前为空（掉线/未挂载）——历史路径 /mnt/e/projects/reap/... 暂不可用"],
                         ["/mnt/f", "F 盘：旧命名（本机无此挂载）→ 见远程 /mnt/gloway"],
                     ]},
                ],
            },
            {
                "id": "p8", "title": "Part 8 · GitHub / HuggingFace / 论文总表",
                "items": [
                    {"type": "table", "id": "t_gh", "title": "GitHub：wufuju2023-cell（10 公开 + 2 私有）",
                     "cols": ["仓库", "简介", "最近推送"],
                     "rows": [
                         ["alpha-proof-original-math-version", "AlphaProof 数学重构档案（21 篇）", "2026-09-09"],
                         ["mcts-theory-learning", "MCTS+RL 数学笔记（模块 1-6）", "2026-09-17"],
                         ["gap-advance-plan-of-nano-proof-v1-m1", "nano 差距/超越/路线分析", "2026-09-15"],
                         ["9-14-project-my-new-linux", "多智能体 AlphaProof 计划与代码（M1-M8）", "2026-09-14"],
                         ["reap-new-update-model", "V1 主仓库（specs + training app + docs）", "2026-09-11"],
                         ["v1-1-agentic-tool", "V1-1 CPU Lean runtime + transports", "2026-09-07"],
                         ["reap-agentic-v1-1", "V1-1 Lean CPU + GPU 桥（工具环证据）", "2026-09-07"],
                         ["new-reap-mcts-ttt-public", "Reap MCTS/元动作/价值头/TTT 公开快照", "2026-09-07"],
                         ["reap-rsi-public", "RSI for Lean proving（脱敏）", "2026-08-27"],
                         ["nanoproof-value-head", "kripner/nanoproof 的 fork（value-head-adapter）", "2026-08-29"],
                         ["reap-alpha-proof（私有）", "reap 工作区 fork（含源码分析 8 篇）", "—"],
                         ["reap-new-update-model-value-head（私有）", "价值头训练工作区", "—"],
                     ]},
                    {"type": "table", "id": "t_hf", "title": "HuggingFace：WufuJu",
                     "cols": ["模型", "说明"],
                     "rows": [
                         ["WufuJu/reap-value-head-v1-scaling", "价值头 v1（scaling 实验）"],
                         ["WufuJu/alpha-proof-open-v1", "开放 v1 相关权重/工件"],
                         ["WufuJu/v1-1-fullv3-artifact", "V1-1 full-v3 工件"],
                         ["WufuJu/internlm2-5-step-prover-critic", "InternLM2.5 step-prover-critic"],
                         ["FrenzyMath/REAL-Prover（基座）", "Qwen2.5-Math-7B 微调；reap 默认 policy/value endpoint 模型"],
                     ]},
                    {"type": "table", "id": "t_refs", "title": "论文与官方资料",
                     "cols": ["资料", "地址"],
                     "rows": [
                         ["AlphaProof（Nature 2025）", "doi:10.1038/s41586-025-09833-y"],
                         ["AlphaProof Nexus（2026）", "arXiv:2605.22763 + github.com/google-deepmind/alphaproof-nexus-results"],
                         ["REAL-Prover", "arXiv:2505.20613 + github.com/frenzymath/REAL-Prover"],
                         ["nanoproof（上游）", "github.com/kripner/nanoproof"],
                         ["REAP（上游）", "github.com/frenzymath/reap · github.com/IQuestLab/reap"],
                     ]},
                ],
            },
        ],
    },
    {
        "id": "m2", "title": "模块二 · 预备知识（按需阅读）",
        "parts": [
            {
                "id": "q1", "title": "Part 1 · Lean 源码学习",
                "items": [
                    C("c_lean_series", "Lean4 源码学习 13 篇（LL-00…12）",
                      "从零到 kernel/meta/tactic：Expr 层级、类型检查器、metavar、monad、tactic 框架、LocalContext……",
                      tags=["预备"],
                      paths=[("wsl", "/home/zhai/project/Lean-source-code-learning-to-know-reap")],
                      quick=[("LL-00 计划", "wsl", "/home/zhai/project/Lean-source-code-learning-to-know-reap/LL-00-README-plan.md"),
                             ("LL-02 Expr", "wsl", "/home/zhai/project/Lean-source-code-learning-to-know-reap/LL-02-expr-levels.md"),
                             ("LL-03 Kernel", "wsl", "/home/zhai/project/Lean-source-code-learning-to-know-reap/LL-03-kernel-type-checker.md"),
                             ("LL-06 Tactic", "wsl", "/home/zhai/project/Lean-source-code-learning-to-know-reap/LL-06-tactic-framework.md")],
                      reads="LL-00→02→03→04→06；再对应 reap-source-code-explain 01"),
                ],
            },
            {
                "id": "q2", "title": "Part 2 · MCTS + RL 数学笔记",
                "items": [
                    C("c_mcts_series", "mcts-theory-learning（15 篇 + 镜像）",
                      "bandit→UCB1→UCT→PUCT→AlphaZero→AlphaProof→Q-transform→主 RL/TTRL/价值头；附梯度/概率/优化基础。",
                      tags=["预备", "核心"],
                      paths=[("remote", "/home/a/文档/mcts-theory-learning")],
                      links=[("github", "https://github.com/wufuju2023-cell/mcts-theory-learning", "GitHub")],
                      quick=[("1 bandit→PUCT", "remote", "/home/a/文档/mcts-theory-learning/1-.md"),
                             ("5 MCTS+RL", "remote", "/home/a/文档/mcts-theory-learning/5-mcts-rl.md"),
                             ("6 AlphaProof", "remote", "/home/a/文档/mcts-theory-learning/6-alpha-proof-mcts-rl.md"),
                             ("8 Q-transform 尺度", "remote", "/home/a/文档/mcts-theory-learning/8-6-q-transform-reason-1.md"),
                             ("9 主RL/TTRL+价值头", "remote", "/home/a/文档/mcts-theory-learning/9-mainrl-ttrl-llm-value-head.md")],
                      reads="1→3→4-3→5→6→7-6→8-6→9；10-15 是梯度/概率/优化复习"),
                ],
            },
            {
                "id": "q3", "title": "Part 3 · 主题参考资料（远程 /home/a/文档/）",
                "items": [
                    {"type": "table", "id": "t_topics", "title": "13 个主题（每个先读 00-导读与目录）",
                     "cols": ["主题", "首读文件", "服务对象"],
                     "rows": [
                         ["Transformer数学理论参考资料", "00-导读与目录.md", "档案 10-11；V1 policy 端点"],
                         ["ttt-参考资料", "00-导读与目录.md", "TTT/RTTT（V1 主线、V2）"],
                         ["样本效率理论参考资料", "00-导读与目录.md", "价值头/课程/样本预算"],
                         ["信息几何理论参考资料", "00-导读与目录.md", "TTT 与 RL 理论背景"],
                         ["RLVR-OPSD-参考资料", "00-总览与阅读路线.md", "GRPO/TTTRL（v1-1-training-methods）"],
                         ["残差连接理论参考资料", "00-导读与目录.md", "网络结构与优化背景"],
                         ["贝叶斯概率与机器学习参考资料", "00-导读与目录.md", "工具环证据（V1-1）/价值"],
                         ["随机微分方程与机器学习参考资料", "00-导读与目录.md", "生成/连续时间背景"],
                         ["高维概率论参考资料", "00-导读与目录.md", "集中不等式/MCTS 理论"],
                         ["扩散模型数学理论参考资料", "00-导读与目录.md", "背景（选读）"],
                         ["LoRA微调数学理论参考资料", "00-导读与目录.md", "V1/V1-1 GPU 训练（LoRA/QLoRA）"],
                         ["RNN-LSTM数学理论参考资料", "00-导读与目录.md", "序列建模背景（选读）"],
                         ["元学习参考资料", "00-导读与目录.md", "TTT/自改进（V1-9/P9）"],
                     ]},
                ],
            },
        ],
    },
]
